### ISSUE TITLE
Method `getFederatedGroupShareProvider` is not defined in lib/AppInfo/Application.php?

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#108]
Split out from #104

**Comment by michielbdejong** [comment]
It should create an instance of https://github.com/SURFnet/rd-sram-integration/blob/main/federatedgroups/lib/FederatedGroupShareProvider.php

**Comment by navid-shokri** [comment]
it is implemented inside branch `issue#93` in line 244

**Comment by michielbdejong** [comment]
A yes, I see it [here](https://github.com/SURFnet/rd-sram-integration/blob/2ffa9f8/federatedgroups/lib/AppInfo/Application.php#L244) (branch: https://github.com/SURFnet/rd-sram-integration/tree/fix/issue%2393)

**Comment by michielbdejong** [comment]
I see it [returns `new \OCA\FederatedGroups\FederatedGroupShareProvider`](https://github.com/SURFnet/rd-sram-integration/blob/2ffa9f8/federatedgroups/lib/AppInfo/Application.php#L265) so that should work correctly once #109 is fixed - great!
