### ISSUE TITLE
Remove unused copy of FederatedShareProvider

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#109]
We still have https://github.com/SURFnet/rd-sram-integration/blob/main/federatedgroups/lib/FederatedFileSharing/FederatedShareProvider.php
But as we saw while working on #104 today, we only use 4 share providers:
* [DefaultShareProvider](https://github.com/pondersource/core/blob/surf-dev/lib/private/Share20/DefaultShareProvider.php)
* [MixedGroupShareProvider](https://github.com/SURFnet/rd-sram-integration/blob/main/federatedgroups/lib/MixedGroupShareProvider.php)
* [Federated(User)ShareProvider](https://github.com/pondersource/core/blob/surf-dev/apps/federatedfilesharing/lib/FederatedShareProvider.php)
* [FederatedGroupShareProvider](https://github.com/SURFnet/rd-sram-integration/blob/main/federatedgroups/lib/FederatedGroupShareProvider.php)

So [`lib/FederatedFileSharing/FederatedShareProvider.php`](https://github.com/SURFnet/rd-sram-integration/blob/main/federatedgroups/lib/FederatedFileSharing/FederatedShareProvider.php) should be removed from the `federatedgroups` app. Right?

**Comment by navid-shokri** [comment]
So, I am suspicious that we have some references to it, but we can examine this and see what will happen.

**Comment by navid-shokri** [comment]
I think that we should have a reference to the [lib/FederatedFileSharing/FederatedShareProvider.php](https://github.com/SURFnet/rd-sram-integration/blob/main/federatedgroups/lib/FederatedFileSharing/FederatedShareProvider.php) in FederatedGroupShareProvider inheritance. 
because we modified this file and sent a share type to the customize Notification class

**Comment by soltanireza65** [comment]
https://github.com/SURFnet/rd-sram-integration/pull/120
@navid-shokri 
please give a review, and merge it if its ok for you
