### ISSUE TITLE
create function in FederatedGroupShareProvider looks wrong

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#110]
It seems that https://github.com/SURFnet/rd-sram-integration/blob/4bfc66aa4c7869a866b26c32b4aa3c35249ed069/federatedgroups/lib/FederatedGroupShareProvider.php#L186 is code that belongs in MixedGroupShareProvider (for local groups that may contain foreign members), not in FederatedGroupShareProvider (for OCM to group).

**Comment by michielbdejong** [comment]
Instead, it should override the behaviour of https://github.com/pondersource/core/blob/surf-dev/apps/federatedfilesharing/lib/FederatedShareProvider.php#L143

**Comment by michielbdejong** [comment]
We should copy the code from https://github.com/SURFnet/rd-sram-integration/blob/4bfc66aa4c7869a866b26c32b4aa3c35249ed069/federatedgroups/lib/FederatedFileSharing/FederatedShareProvider.php#L155 and paste it into this file

**Comment by navid-shokri** [comment]
I just did this Issue.
