### ISSUE TITLE
Consider linking oc_share_external_group to oc_share_external for existing fields

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#118]
@FlorisFokkinga had a good idea, we can make `oc_share_external_group` link to `oc_share_external` with a foreign key, then we avoid a lot of `shareId` headaches. Basically, the downside is that you have to do two inserts (one into `oc_share_external_group` and one into `oc_share_external`) and you need to do a JOIN query to get all the information about a share. But the good thing is it instantly solves issues like #106

@navid-dada @soltanireza65 what do you think?

**Comment by soltanireza65** [comment]
To me it sounds good
And as a plus, we should use transactions and commit the changes more accurately

**Comment by navid-shokri** [comment]
So, It Sounds like we should review or maybe change a big part of our efforts. From a technical point of view, it is another option that can make our request steering easier but I am Ensure that it has its own downside also those are not clear to us until now.

from the product aspect, I think this is the third or fourth option that we are examining, and I think we need to put more time to sharpen our saw before cutting the tree.

**Comment by michielbdejong** [comment]
It would be a bit of work, but it would also fix #106 so that would be an advantage!

**Comment by michielbdejong** [comment]
Let's close this because we think we don't need it for #106 - we can reopen it if we find another reason why we need it.
