### ISSUE TITLE
Resharing in federated group is not fully functional.

### ISSUE THREAD

**Issue by navid-shokri** [SURFnet/rd-sram-integration#136]
In typical cases such as OCM-user or local user, Resharing flows these behaviors should be obvious: :information_source: 
**Example Scenario:** **user1** shared file `myfile.txt` with **user2** and now **user2** want to share incoming file `myfile.txt` with **user3**

1- file should be shared with a new participant (**user3**) and the share owner should be set to the original file maintainer(**user1**).
2- **user3** should be listed in the *shared with list* of the `myfile.txt` file in owner (**user1**) panel.
3- Also, **user3** should be listed in the *shared with list* of the `myfile.txt` in (**user2**) panel.

**Comment by navid-shokri** [comment]
So, after investigating inside oc1.docker  (**user3**) there is this repetitive error: 

```{"reqId":"qgMNvskZ09QWnmJCdf0J","level":3,"time":"2023-04-04T16:14:01+00:00","remoteAddr":"172.18.0.2","user":"einstein","app":"PHP","method":"POST","url":"\/index.php\/apps\/files_sharing\/api\/externalShares","message":"Undefined index: password at \/var\/www\/html\/apps\/files_sharing\/lib\/External\/Storage.php#92"}```

**Comment by navid-shokri** [comment]
It seems that we have problem there :information_source: 

https://github.com/pondersource/core/blob/0d7441422741142a248fe6184794c81c5abed06a/apps/federatedfilesharing/lib/FederatedShareProvider.php#L187

**Comment by navid-shokri** [comment]
So, another clue is just found. 

https://github.com/pondersource/core/blob/5af5d3ad73245391c9d34fd85a6b2040f09a3407/lib/private/Share20/Manager.php#L818

in this line, if the incoming share type is SHARE_TYPE_REMOTE the federatedShareProvider would be chosen, the wrong table (`oc_share_external`) will be queried and ShareNotFound will be raised while the query should be execute on `oc_share_external_group`
ن

**Comment by yasharpm** [comment]
Resharing is fully done and functional now. The test code for it is applied [here](https://github.com/pondersource/oc-opencloudmesh/commit/5c8297d5e77873a2564e6980da902e002f5f333b).
