### ISSUE TITLE
share back to the share owner is allowed in federated group sharing (unexpected behavior)

### ISSUE THREAD

**Issue by navid-shokri** [SURFnet/rd-sram-integration#137]

**Comment by thepeak99** [comment]
Needs testing and reviewing

**Comment by soltanireza65** [comment]
![Image](https://github.com/SURFnet/rd-sram-integration/assets/53468377/9adca891-6d3e-4a0e-8f1d-3f46cd55a82f)

**Comment by soltanireza65** [comment]
as you can see when we want to reshare a federated share to its owner
is allowed (but with an error in reshare side(Marie)) 
and also we can accept it in owner side

**Comment by navid-shokri** [comment]
We should check the desired functionality in the Nextcloud.
So you should run two instances of Nextcloud and share a file with the remote group, then reshare it and find out the standard mind set.

**Comment by yasharpm** [comment]
After much investigation:

Resharing a group share is not implemented in NextCloud. Throughout the code, this case is ignored and the 2 related endpoints `/ocm/notifications` and `/shares/{id}/reshare` return 403 and 400 error codes respectively. After the receiver tries to reshare and calls these 2 end points, in results in an invalid error message that reads "File is already shared with {whatever}" regardless of the validity of the share target.

**Comment by shokri-navid** [comment]
@michielbdejong @thepeak99 what should we do in this scenario?

**Comment by yasharpm** [comment]
Results of testing the same thing using our OCM to groups app:
Resharing a received user share or group share to a group on the provider side that the provider also is a member of, works. The provider accepts the share and it sits in their files. The provider can see that they have shared the file with both the receiver and the group on the local server.
Resharing a received user share or group share back to the provider user does not work. As it shouldn't. The error message says that the file is already shared with the receiver which is the correct message. And the original provider does not show any notifications to accept an incoming share which it correctly shouldn't.

**Comment by yasharpm** [comment]
Next stop: Test it with the federated groups enabled.

**Comment by yasharpm** [comment]
The behavior is exactly the same with the federated groups app enabled. @soltanireza65 it means that I could not reproduce the bug you reported: share notification still popping up for the original provider. Please check again.

If the bug is actually not there, then I think we just improved OC group sharing to be better than NC. I don't see any unexpected or unwanted behavior here.
