### ISSUE TITLE
decline share functionality is not matched with the original behavior

### ISSUE THREAD

**Issue by navid-shokri** [SURFnet/rd-sram-integration#141]
on user-OCM Sharing this is the behavior: :information_source: 

**user1@oc1.docker** shares a file with **user2.oc2.docker**. BUT, **user2@oc2.docker** will decline the share. in this scenario:

1- the share entry will be deleted from `oc_share` table in DB of the `oc1.docker`.
2- the share entry will be deleted from `oc_share` table in DB of the `oc2.docker`

**Comment by navid-shokri** [comment]
But, in group-OCM when we are declining the shared file even if all share recipients decline the share request all of the entries will stay in the databases. :red_circle:

**Comment by thepeak99** [comment]
Behavior changed.
