### ISSUE TITLE
What if reshare happens to a group that the owner belongs to?

### ISSUE THREAD

**Issue by navid-shokri** [SURFnet/rd-sram-integration#142]
assume this scenario: 

`user1@oc1` that belongs to `group1` share a file with an entity (user/group) on `oc2` and then the `user2@oc2` share the file again with `group1@oc1`? :question: 

what should be our reaction?

**Comment by michielbdejong** [comment]
> In other words

I don't think you accurately reworded Navid's question, I think you gave an answer to it! :)

> I have come up with 3 solutions

I think you listed 3 code architectures here

> federatedfilesharing app can be totally modified

How does that option affect our goal of keeping the changes we make in owncloud/core to a minimum? Remember this app is part of owncloud/core, so al we're allowed to do in it is insert if-statements (or catch-statements, I think that's fine too) that divert the code path if one or both of our apps are installed, and that do nothing otherwise.

**Comment by michielbdejong** [comment]
@yasharpm regarding your discussion about code architecture, maybe you can split that out to a separate issue?

And regarding @navid-shokri 's original question, I think we should test how it is handled if this happens on a single server:
`user1@oc1` that belongs to `group1` share a file with an entity (user/group) that is also on `oc1` and then the `user2@oc1` share the file again with `group1@oc1`? :question: 

I think that, although resharing to the resource owner is prohibited, resharing to a group of which the resource owner is a member is not. So we don't have to do any lookups regarding group memberships of `user1@oc1`, we can just let the reshare happen.

I think processing of reshare-request notifications is already implemented on the sender side, and our additional share type should not have much effect on that code, right? The only thing we need to add is reshare to a remote group (for @yasharpm's OCM app) and reshare to a mixed group (for @navid-shokri's FG app). In both cases, the answer to "what if reshare happens to a group that the owner belongs to?" is, I think "no special requirements, just reshare as usual"! :)

**Comment by yasharpm** [comment]
> I don't think you accurately reworded Navid's question, I think you gave an answer to it!

It's getting closer to understanding the question and hence the answer.

> I think processing of reshare-request notifications is already implemented on the sender side, and our additional share type should not have much effect on that code, right?

There is a fundamental problem here. Different share type implementations need to be aware of each other. If I want to share something to a user that has been shared with me as a group, the reshare to user logic has to find the share in the shared to group table (i.e. `share_external_group`). This is valid for all reshares from one share type to another.

> I think you listed 3 code architectures here
> How does that option affect our goal of keeping the changes we make in owncloud/core to a minimum

Hence we can not longer be as passive to OC managers' liking. If we want share to groups to work, we have no choice but to change federatedfilesharing in a way that respects a deeper level of intervention. Or completely steal the control from it which is solution 2.

**Comment by michielbdejong** [comment]
> If I want to share something to a user that has been shared with me as a group, the reshare to user logic has to find the share in the shared to group table (i.e. share_external_group)

Ah but that is for the process at the receiver's side, that leads up to sending the reshare-request notification.
The way I understood the OP's question was strictly about how the sending side should handle a reshare-request notification, once it arrives?

**Comment by yasharpm** [comment]
Ah I think I had to create a separate issue! Apologies, just because the issue was related and recent, I assumed it is about the issue I raised.
Regarding the way it is handled, it's like a chain. When we receive a reshare request, we check if we are the owner or the file has been shared with us. If it is shared, we forward the call to whom shared it with us. The chain breaks if we can not find a share from the other type.

**Comment by michielbdejong** [comment]
As discussed, we are not going to work on this issue during this sprint.
Once we do have time to look into this, we should first observe, and then generalise from what we see.
So we have three things to look at:
* suppose user1@oc1 shares with user2@oc1 and user2@oc1 requests a reshare with group1@oc1. What happens? Is a local user-to-group share created.
* suppose user1@oc1 shares with user2@oc2 and user2@oc2 requests a reshare with user3@oc1. What happens? Is a local user-to-user share created?
* on Nextcloud, suppose user1@oc1 shares with group2@oc2 and user2@oc2 requests a reshare with user3@oc1. How does Nextcloud deal with reshare after user-to-group OCM?
