### ISSUE TITLE
Basic testnet with OIDC and LDAP

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#143]
Create a testnet setup with 1 OIDC server, 1 LDAP server, 3 ownCloud servers, 2 users per ownCloud server, and some different groups (both local ones and federated ones).

Task for 13 April: move the OIDC and LDAP servers into the existing testnet
Task for 14 April: add oc3.docker, create users, create groups.

@soltanireza65 estimates an 80% chance that this will be done by EOB tomorrow.

working on this on https://github.com/SURFnet/rd-sram-integration/tree/feat/oidc-ldap

**Comment by soltanireza65** [comment]
things to do for the first phase:
- create a 3rth OC container and attach it to testnet
- create a LDAP server and attach it to testnet

**Comment by soltanireza65** [comment]
maybe we need to add a phpLdapAdmin to working easily with LDAP

**Comment by soltanireza65** [comment]
sync ldap users with owncloud
```bash
sudo -u www-data php occ user:sync "OCA\User_LDAP\User_Proxy"
```

**Comment by soltanireza65** [comment]
Configuration
![image](https://user-images.githubusercontent.com/53468377/232749366-192e4843-f3cc-48b5-9435-f0c316f86c66.png)
![image](https://user-images.githubusercontent.com/53468377/232749555-ebc482cb-52bc-4c9d-b53a-8e23d13692e8.png)

**Comment by soltanireza65** [comment]
![image](https://user-images.githubusercontent.com/53468377/232995027-d9fb0bd5-5fb9-4af5-a79a-8b678fc91bc7.png)

**Comment by soltanireza65** [comment]
![image](https://user-images.githubusercontent.com/53468377/232995982-c422e1d0-51a9-49b6-b14a-4b4ac137d7d8.png)

**Comment by soltanireza65** [comment]
![image](https://user-images.githubusercontent.com/53468377/232996371-c8430834-01a2-48f6-98c0-8e8d783e0847.png)

**Comment by michielbdejong** [comment]
Done
