### ISSUE TITLE
Provisioning filter

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#144]
Don't allow e.g. aad@almere.net to log in to e.g. bergambacht.net (only to almere.net)
We don't know yet how we are going to do this, so first step is exploration.

**Comment by michielbdejong** [comment]
@soltanireza65 @navid-dada is it clear to you what the goal is here?
Can you brainstorm some possible solution approaches so we can pick the best option?

**Comment by soltanireza65** [comment]
maybe we should lookup users who there email address includes the phrase

**Comment by michielbdejong** [comment]
yes! and then how can you make sure that login is blocked based on that email address except on 1 of the 3 servers?

**Comment by soltanireza65** [comment]
we do have access to the origin

**Comment by soltanireza65** [comment]
is this the expected senarion:
block user with email `aad@almere.net` on owncloud instance with origin `almere.net`?

**Comment by michielbdejong** [comment]
no, `almere.net` should be the only server that `aad@almere.net` is allowed to log in to.
Yes, to match the domain we can look at the origin of the request, although it would be even simpler to just add an env var or a config var for it.
On the user attribute side, it may be email address, or maybe affiliation attribute that we look at (the latter would be closer to how SRAM works).
I can think of a few points where you could add this restriction:
* just before the deploy that happens when `aad@almere.net` logs in via OIDC for the first time, add an `if`-statement that aborts the process if the domain doesn't match
* allow the account to be deployed (a bit ugly), but in the OIDC login app, somehow prevent login to it (so that it would still work)
* allow the person to log in, but they would not receive any shares (this would be even uglier and probably undesired) - although we could actually just say that in reality either SurfConext whitelisting or something like a global-site-selector app will take care of the domain check

Can you dig into the code and see if you can find the point where deploy happens and the point where login happens?

**Comment by soltanireza65** [comment]
now we have two login procedure 
1. Login with OIDC (LDAP users)
2. Login with owncloud (LDAP users, and without the need for OIDC)


in the case 2, we do have LoginController, and totally own Controll of the user before he/she try to login

**Comment by soltanireza65** [comment]
o wait
actually, it would be easy as LDAP filters

**Comment by soltanireza65** [comment]
(|(displayName=*allowed*)(mail=*allowed*)(uid=*allowed*)(givenname=*allowed*)(sn=*allowed*)(cn=*allowed*))

**Comment by michielbdejong** [comment]
But if LDAP is filtered per server then the server will not know about foreign group members... 🤔 
Let's have a video call to discuss!

**Comment by navid-dada** [comment]
Reza can you let us know about this picture that you sent? it is the final result of your task or what?

**Comment by soltanireza65** [comment]
Yes, of course, I will clean up the issue with clear comments
But for now we have it working.

**Comment by michielbdejong** [comment]
Done
