### ISSUE TITLE
Fix Sharee Search GUI

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#147]
I think this is a problem in https://github.com/owncloud/core/pull/40589 and not in https://github.com/pondersource/oc-opencloudmesh right?
<img width="288" alt="Screenshot 2023-04-14 at 15 25 59" src="https://user-images.githubusercontent.com/408412/232056435-6a1f9014-1390-4b09-9c23-5c0a0ddea63d.png">

**Comment by navid-shokri** [comment]
seems is changed :thinking: 
https://pondersource.slack.com/files/U02R8E3PMA8/F053X502THP/image.png

**Comment by navid-shokri** [comment]
https://github.com/pondersource/oc-opencloudmesh/blob/5df71fb1bb799d5e30a394d9811a07d75dcd0401/opencloudmesh/lib/ShareeSearchPlugin.php#L186
https://github.com/pondersource/oc-opencloudmesh/blob/5df71fb1bb799d5e30a394d9811a07d75dcd0401/opencloudmesh/lib/ShareeSearchPlugin.php#L193
I don't know where these `G:` and `U:` come from. 
@michielbdejong  It seems you choose a wrong code reference

**Comment by michielbdejong** [comment]
Yes, see that commit ^

**Comment by navid-dada** [comment]
I did not done any special I just run it. may be you are running the code in your browser (not a headless firefox tester) and it has its own cache.
