### ISSUE TITLE
OC PR JS tests failing 

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#150]
```
Firefox 112.0 (Ubuntu 0.0.0) OCA.Sharing external tests show dialog for each share to confirm sends accept info to server on confirm FAILED
	Expected object not to have properties
	    share_type: 'user'
	@apps/files_sharing/tests/js/externalSpec.js:177:18
Firefox 112.0 (Ubuntu 0.0.0) OCA.Sharing external tests show dialog for each share to confirm sends delete info to server on cancel FAILED
	Expected '/owncloud/index.php/apps/files_sharing/api/externalShares/123?share_type=user' to equal '/owncloud/index.php/apps/files_sharing/api/externalShares/123'.
	@apps/files_sharing/tests/js/externalSpec.js:202:24
```
https://drone.owncloud.com/owncloud/core/38296/8/5

@navid-dada I think the rest of the test failures are because they ran in parallel and were killed when this test fails.

**Comment by navid-shokri** [comment]
actually no, I ran tests on my codespace separately and they were failing too.
so we should check all of them one by one. So, my workaround to resolving the tests will be on this branch:
https://github.com/pondersource/core/tree/fix-tests

**Comment by michielbdejong** [comment]
@navid-shokri and @soltanireza65, as discussed in the standup, there are a number of other tests that also fail when you run the tests locally. Please fix the test that fails in 
https://drone.owncloud.com/owncloud/core/38296/8/5 asap, so we can see these other failing tests in CI as well.
