### ISSUE TITLE
discuss about handleing new federal group members

### ISSUE THREAD

**Issue by soltanireza65** [SURFnet/rd-sram-integration#152]
let's discuss why we should handle resharing files on the receiver side
if our OCM app could approach the existing shared items to new entry group members then we don't need to handle it on each sender side
this should decrees the API calls in between `OC` instances by far
and decreed the complexity of the interactions between building blocks(OCM share, RD_SRAM)

**Comment by yasharpm** [comment]
Fixed in [this commit](https://github.com/pondersource/oc-opencloudmesh/commit/5d85b48612495d1834fd8872cd1b0e3c3e611a09).
