### ISSUE TITLE
Check if we are treating incoming group member name as full OCM users

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#159]
E.g. jan@harderwijk.com
Or jan@gmail.com@harderwijk.com

**Comment by T0mWz** [comment]
So we send to both always the same federated userid
[oc1.docker.com](http://oc1.docker.com/)
 [pietje@example.com](mailto:pietje@example.com)@oc1.docker.com
 [klaas@example.de](mailto:klaas@example.de)@oc2.docker.com
[oc2.docker.com](http://oc2.docker.com/)
 [pietje@example.com](mailto:pietje@example.com)@oc1.docker.com
 [klaas@example.de](mailto:klaas@example.de)@oc2.docker.com
Then we can check on an instance, if federated domain is eagle, then it's a local user

**Comment by yasharpm** [comment]
> 1. user name without @ is always local
> 2. username with a single @ can be local user (where email is username) or a federated user.
  Here, ask local owncloud of it knows this user. If false, then federated user
> 3. username with double @ is always a federated

@T0mWz @michielbdejong I think we can follow this logic.
