### ISSUE TITLE
exception raise on `accept share notification` on sender (OC1) side

### ISSUE THREAD

**Issue by shokri-navid** [SURFnet/rd-sram-integration#165]
this exception will raise on sender side( oc1 ) if the receiver accept the incoming share. :information_source: 

{"reqId":"gHyU92zMJz37aPmSXBmo","level":3,"time":"2023-05-18T08:18:52+00:00","remoteAddr":"172.18.0.5","user":"--","app":"federatefilesharing","method":"POST","url":"\/index.php\/apps\/federatedfilesharing\/notifications","message":"server can not process notification, Unspecified share exception"}

**Comment by navid-shokri** [comment]
this error disappeared.
