### ISSUE TITLE
Check notification app side effects on our app.

### ISSUE THREAD

**Issue by navid-shokri** [SURFnet/rd-sram-integration#171]
:warning: 
according to this Issue
https://github.com/pondersource/nc-sciencemesh/issues/319

if the notification app is enabled the new shred popup will not be shown and the Notification application is in charge of informing the user of new incoming shares. so
so, it seems necessary to check our app integration with Notification APP.

**Comment by michielbdejong** [comment]
Related to #84 ?

**Comment by soltanireza65** [comment]
@shokri-navid 
I've just installed the `https://github.com/owncloud/notifications` app in two OC instances,
Logged in to oc1.docker as Einstein
shared a folder with marie@oc2.docker


![Image](https://github.com/SURFnet/rd-sram-integration/assets/53468377/9bc36c1c-84e7-48d2-8cfd-a9655a303887)

notification is showing as expected
and Also we can accept the share successfully



![Image](https://github.com/SURFnet/rd-sram-integration/assets/53468377/de2683f0-ffa9-41e7-ba9a-a795ef6e769f)


so there is no side effects in file sharing with notifications, right?
