### ISSUE TITLE
how to distinguish between default group backend and federated group backends?

### ISSUE THREAD

**Issue by soltanireza65** [SURFnet/rd-sram-integration#178]
first of all: we should all agree that all the groups on all tables should be unique,

by default,  ownCloud just has one group-type, and the default groupManager class will return just the default group type.
also, we know that the getBackend method of the default group returns the first index of the registered backends array 
but now that we have a second type of group ('fg-group')
when the group manager tries to get the group, it should be able to assign the correct backend to the given group.

working on this in:
https://github.com/SURFnet/rd-sram-integration/tree/new-group-backend

**Comment by michielbdejong** [comment]
This is a question you're posing in relation to #180, right?

**Comment by soltanireza65** [comment]
we have fixed it in https://github.com/SURFnet/rd-sram-integration/pull/185
