### ISSUE TITLE
owncloud init script failing

### ISSUE THREAD

**Issue by soltanireza65** [SURFnet/rd-sram-integration#179]
executing init.sh on oc1.docker
ownCloud was successfully installed
No such app enabled: firstrunwizard
Installing Custom Groups
PHP Notice:  Undefined index: HTTP_HOST in /var/www/html/config/config.php on line 9
PHP Stack trace:
PHP   1. {main}() /var/www/html/console.php:0
PHP   2. require_once() /var/www/html/console.php:74
PHP   3. OC::init() /var/www/html/lib/base.php:1059
PHP   4. OC::initPaths() /var/www/html/lib/base.php:531
PHP   5. OC\Config->__construct() /var/www/html/lib/base.php:135
PHP   6. OC\Config->readData() /var/www/html/lib/private/Config.php:64
PHP   7. include() /var/www/html/lib/private/Config.php:255
customgroups enabled
Installing OpenCloudMesh
PHP Notice:  Undefined index: HTTP_HOST in /var/www/html/config/config.php on line 9
PHP Stack trace:
PHP   1. {main}() /var/www/html/console.php:0
PHP   2. require_once() /var/www/html/console.php:74
PHP   3. OC::init() /var/www/html/lib/base.php:1059
PHP   4. OC::initPaths() /var/www/html/lib/base.php:531
PHP   5. OC\Config->__construct() /var/www/html/lib/base.php:135
PHP   6. OC\Config->readData() /var/www/html/lib/private/Config.php:64
PHP   7. include() /var/www/html/lib/private/Config.php:255
opencloudmesh enabled
Installing Federated Groups
PHP Notice:  Undefined index: HTTP_HOST in /var/www/html/config/config.php on line 9
PHP Stack trace:
PHP   1. {main}() /var/www/html/console.php:0
PHP   2. require_once() /var/www/html/console.php:74
PHP   3. OC::init() /var/www/html/lib/base.php:1059
PHP   4. OC::initPaths() /var/www/html/lib/base.php:531
PHP   5. OC\Config->__construct() /var/www/html/lib/base.php:135
PHP   6. OC\Config->readData() /var/www/html/lib/private/Config.php:64
PHP   7. include() /var/www/html/lib/private/Config.php:255
federatedgroups enabled
Editing Config
maria2.docker port 3306 is open
oc2.docker port 443 is open

**Comment by michielbdejong** [comment]
Thanks for opening this issue! We can work around it for now but we obviously want to fix this eventually - also for instance when we will be putting our test runs into GitHub Actions!

**Comment by michielbdejong** [comment]
https://github.com/pondersource/dev-stock/blob/main/scripts/testing-rd-sram.sh#L48 seems to be running only that
