### ISSUE TITLE
Sharing with a via SCIM create group doesn't work

### ISSUE THREAD

**Issue by T0mWz** [SURFnet/rd-sram-integration#184]
Created a group with only local users on same environment;

Create a share;
```
{"reqId":"ZIHD7XTqQg8xLkRoogEv8AAAABA","level":3,"time":"08\/Jun\/2023:14:05:02","remoteAddr":"10.234.2.58","user":"surfsara","app":"no app in context","method":"POST","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json","message":"Failed to notify remote server of mixed group share, panic (Sharing testmap failed, could not find TestGroup (uniharderwijk_surfdrive_test) (SRAM CO), maybe the server is currently unreachable.)"}
```
![Screenshot 2023-06-08 at 14 05 04](https://github.com/SURFnet/rd-sram-integration/assets/2477797/2f645e50-8022-472c-99a2-604f3085b2b2)

Delete the share

```
{"reqId":"ZIHDg11QfCRhkVbqfOOH1wAAAAQ","level":3,"time":"08\/Jun\/2023:14:03:17","remoteAddr":"10.234.2.58","user":"surfsara","app":"no app in context","method":"DELETE","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares\/2325?format=json","message":"Failed to notify remote server of mixed group share, panic (Unsharing testmap failed, could not find TestGroup (uniharderwijk_surfdrive_test) (SRAM CO), maybe the server is currently unreachable.)"}
```

![Screenshot 2023-06-08 at 14 03 24](https://github.com/SURFnet/rd-sram-integration/assets/2477797/0466fa95-f79d-4b6c-b4dc-8cea5c27b8ba)

**Comment by soltanireza65** [comment]
@T0mWz  what do you mean by Share with SCIM?

**Comment by michielbdejong** [comment]
I think the steps to reproduce would be:
1. create a group through SCIM
2. share a file or folder with that group
3. delete that share

**Comment by T0mWz** [comment]
> I think the steps to reproduce would be:
> 
> 1. create a group through SCIM
> 2. share a file or folder with that group
> 3. delete that share

Correct!

Can you not better add the usernames here as the really are and set a `#` for the remote host?
```
MariaDB [miskatonic_tst_oc]> select * from oc_group_user where uid like '%#%';
+---------------------------------------------------------+------------------+
| gid                                                     | uid              |
+---------------------------------------------------------+------------------+
| Demo collaboration (uniharderwijk_democollab) (SRAM CO) | breek001#surf.nl |
| Demo collaboration (uniharderwijk_democollab) (SRAM CO) | es000003#surf.nl |
| Demo collaboration (uniharderwijk_democollab) (SRAM CO) | reint001#surf.nl |
| Demo collaboration (uniharderwijk_democollab) (SRAM CO) | zoete001#surf.nl |
| TestGroup (uniharderwijk_surfdrive_test) (SRAM CO)      | wezep001#surf.nl |
| TestGroup (uniharderwijk_surfdrive_test) (SRAM CO)      | zoete001#surf.nl |
+---------------------------------------------------------+------------------+
```

**Comment by michielbdejong** [comment]
@T0mWz `tst-aperture.data.surfsara.nl` is the receiving server, right?
Can you confirm whether at least the opencloudmesh app is installed there?

**Comment by T0mWz** [comment]
@michielbdejong @soltanireza65  
Yes, opencloudmesh 0.1.0 and federatedgroups are installed there too.

**Comment by T0mWz** [comment]
But what are your usernames? @michielbdejong @soltanireza65 
See also https://github.com/SURFnet/rd-sram-integration/issues/159

Basically all our usernames have an `@`-sign by default... I'm affraid you have not usernames with an `@` sign..?

**Comment by michielbdejong** [comment]
@navid-shokri can you confirm that when you're testing this in dev-stock, you are using usernames that include @-signs?
Also, it seems from https://github.com/SURFnet/rd-sram-integration/issues/184#issuecomment-1582611787 that Tom's group is in the wrong db table, right?

**Comment by T0mWz** [comment]
However these users (wezep001@surf.nl and zoete001@surf.nl) are both on the same OC instances (tst-miskatonic by the way), so these are just local users where a SCIM group is created for. OCM is not yet involved here. 
So what I try to say here;

> > I think the steps to reproduce would be:
> > 
> > 1. create a group through SCIM
> > 2. share a file or folder with that group
> > 3. delete that share
> 
> Correct!
> 
> Can you not better add the usernames here as the really are, so with an `@`. And set a `#` for the remote host? Then the normal OC share still keep working, then you only have to add the knowledge for federated group shares and is this table just fine.
> 
> ```
> MariaDB [miskatonic_tst_oc]> select * from oc_group_user where uid like '%#%';
> +---------------------------------------------------------+------------------+
> | gid                                                     | uid              |
> +---------------------------------------------------------+------------------+
> | Demo collaboration (uniharderwijk_democollab) (SRAM CO) | breek001#surf.nl |
> | Demo collaboration (uniharderwijk_democollab) (SRAM CO) | es000003#surf.nl |
> | Demo collaboration (uniharderwijk_democollab) (SRAM CO) | reint001#surf.nl |
> | Demo collaboration (uniharderwijk_democollab) (SRAM CO) | zoete001#surf.nl |
> | TestGroup (uniharderwijk_surfdrive_test) (SRAM CO)      | wezep001#surf.nl |
> | TestGroup (uniharderwijk_surfdrive_test) (SRAM CO)      | zoete001#surf.nl |
> +---------------------------------------------------------+------------------+
> ```

I should not replace the `@` with an `#` where these users are just local and then normal group share can handle that well too.

```
MariaDB [miskatonic_tst_oc]> select * from oc_accounts where user_id like 'wezep%';
+------+-------+------------------+------------------+------------------+-------+------------+------------------+-----------------------------------------+-------+---------------+
| id   | email | user_id          | lower_user_id    | display_name     | quota | last_login | backend          | home                                    | state | creation_time |
+------+-------+------------------+------------------+------------------+-------+------------+------------------+-----------------------------------------+-------+---------------+
| 1050 | NULL  | wezep001@surf.nl | wezep001@surf.nl | wezep001@surf.nl | NULL  |          0 | OC\User\Database | /var/www/owncloud/data/wezep001@surf.nl |     1 |    1683889007 |
+------+-------+------------------+------------------+------------------+-------+------------+------------------+-----------------------------------------+-------+---------------+
1 row in set (0.001 sec)
```

**Comment by navid-shokri** [comment]
why are your users stored in oc_group_user? according to our new version, all of them should be stored in oc_fg_group_user. :thinking: 
@T0mWz

**Comment by T0mWz** [comment]
Uh, I don't do that.. I just create a group via SCIM/ your federatedgroups. 😉

**Comment by navid-shokri** [comment]
So I send this request to my SCIM controller:
```curl
curl --request POST \
  --url http://localhost:42319/index.php/apps/federatedgroups/scim/Groups \
  --header 'Content-Type: application/json' \
  --header 'x-auth: Bearer VGfRewYoHu6lTCoVSAQ6GevfGYznIBZT' \
  --cookie 'ocvzvyc9ti1g=3ke8v4tvguika5b618elqodovu; ocp9eud6ezkt=u2b56ls1bpt8d57vcloe1c6q0m; oci50bcnk8nq=gjjhcavr17mcff3vadvjdn47uk; ocxougkoe4sh=hu5ve2k0i03jvoobct7h7gapfk' \
  --data '{
  "members": [
    {
      "value": "navid@pondersource.com@oc2.docker"
    },
		{
      "value": "Tom@surfnet.nl@oc2.docker"
    }
  ],
  "id": "IssueNo184"
}'
```


**And it is my tables :**


```md
MariaDB [efss]> select * from oc_fg_groups;
+------------+
| gid        |
+------------+
| IssueNo184 |
+------------+
1 row in set (0.000 sec)

MariaDB [efss]> select * from oc_fg_group_user;
+------------+-----------------------------------+
| gid        | uid                               |
+------------+-----------------------------------+
| IssueNo184 | navid@pondersource.com#oc2.docker |
| IssueNo184 | Tom@surfnet.nl#oc2.docker         |
+------------+-----------------------------------+
2 rows in set (0.000 sec)
```

**Comment by navid-shokri** [comment]
:boom: 
@T0mWz are you sure you have the same group name on receiving party? 
I shared a file with the `IssueNo184` group in my testing environment despite there being no same group name and guess what?


> Sharing images.jpg failed, could not find IssueNo184, maybe the server is currently unreachable.

**Comment by T0mWz** [comment]
> So I send this request to my SCIM controller:
> 
> ```
> curl --request POST \
>   --url http://localhost:42319/index.php/apps/federatedgroups/scim/Groups \
>   --header 'Content-Type: application/json' \
>   --header 'x-auth: Bearer VGfRewYoHu6lTCoVSAQ6GevfGYznIBZT' \
>   --cookie 'ocvzvyc9ti1g=3ke8v4tvguika5b618elqodovu; ocp9eud6ezkt=u2b56ls1bpt8d57vcloe1c6q0m; oci50bcnk8nq=gjjhcavr17mcff3vadvjdn47uk; ocxougkoe4sh=hu5ve2k0i03jvoobct7h7gapfk' \
>   --data '{
>   "members": [
>     {
>       "value": "navid@pondersource.com@oc2.docker"
>     },
> 		{
>       "value": "Tom@surfnet.nl@oc2.docker"
>     }
>   ],
>   "id": "IssueNo184"
> }'
> ```
> 
> **And it is my tables :**
> 
> ```lisp
> MariaDB [efss]> select * from oc_fg_groups;
> +------------+
> | gid        |
> +------------+
> | IssueNo184 |
> +------------+
> 1 row in set (0.000 sec)
> 
> MariaDB [efss]> select * from oc_fg_group_user;
> +------------+-----------------------------------+
> | gid        | uid                               |
> +------------+-----------------------------------+
> | IssueNo184 | navid@pondersource.com#oc2.docker |
> | IssueNo184 | Tom@surfnet.nl#oc2.docker         |
> +------------+-----------------------------------+
> 2 rows in set (0.000 sec)
> ```
> 
> So It seems there is a problem with Tom's version. @michielbdejong

Will update my app, it's version of yesterday. Don't know if something is changed what can be related..

**Comment by navid-shokri** [comment]
but I ran the same request and it worked :exploding_head: 

https://github.com/SURFnet/rd-sram-integration/issues/184#issuecomment-1584188270

**Comment by michielbdejong** [comment]
I was able to reproduce it \o/

<img width="1048" alt="Screenshot 2023-06-09 at 13 05 33" src="https://github.com/SURFnet/rd-sram-integration/assets/408412/452fe25e-e5dd-4efe-9c10-3a27b42557f3">

@navid-shokri shall we do a screensharing now to go fix it?

**Comment by michielbdejong** [comment]
Ah bummer it was because of https://github.com/pondersource/dev-stock/commit/97e9728b82c467f230d4d22d8ee46a07b27d235e
Back to testing.

**Comment by michielbdejong** [comment]
It seems the original issue was fixed by updating the app but now there are two new problems. Splitting those out: #190 and #191.
