### ISSUE TITLE
Group is created but users are not

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#190]
See https://github.com/SURFnet/rd-sram-integration/issues/184#issuecomment-1584221776

**Comment by michielbdejong** [comment]
This was due to database replication. If Tom removes the db proxy then this problem goes away.
To fix it in general (so that it also works with a db proxy) we should use the cache in the group backend.
We fill it here: https://github.com/SURFnet/rd-sram-integration/blob/2207762/federatedgroups/lib/GroupBackend.php#L97
But we don't read it here: 
https://github.com/SURFnet/rd-sram-integration/blob/2207762/federatedgroups/lib/GroupBackend.php#L148

**Comment by navid-shokri** [comment]
can we close this Issue? 
@michielbdejong

**Comment by thepeak99** [comment]
The customer wants to use it with a DB cluster. We have to check that it works.

**Comment by thepeak99** [comment]
We should not assume that our inserts will pop up in subsequent selects. 

Also we need to create a test for this.

**Comment by thepeak99** [comment]
duplicate of #197
