### ISSUE TITLE
Regular User Report

### ISSUE THREAD

**Issue by parhamin2010** [SURFnet/rd-sram-integration#208]
# **Overall review**
1- On installation docs page, first item, there is a chack word (search for chack).
2- There's no information regarding the user case story. it will help users to find out what is question and what is answerd by this solution.

# **API**

7- For SCIM Controller once I run a getGroups endpoint, it needs x-auth header. (not mentioned clearly!) it's located inside the oc_appconfig and called scim_token)
8-  Document for SCIM is not clear enough:
	in docs: `curl --location '/index.php/apps/federatedgroups/scim/Groups'`
	in real: `curl --location --request GET 'https://oc1.docker/index.php/apps/federatedgroups/scim/Groups' --header 'x-auth: Bearer something-super-secret' `
	
## Endpoints:
1- [CreateGroup](https://github.com/SURFnet/rd-sram-integration/blob/mix-provider/ScimControllerDocs.md#creategroup): it is not explained well in [docs](https://github.com/SURFnet/rd-sram-integration/blob/mix-provider/ScimControllerDocs.md#creategroup). Also the request is POST not PUT. 
2- [DeleteGroup](https://github.com/SURFnet/rd-sram-integration/blob/mix-provider/ScimControllerDocs.md#deletegroupgroupid) after run this, no response returned.

**For all routes it needs json header to be specified.**

---------------
1- When admin created a custom group http://oc1.docker/index.php/settings/personal?sectionid=customgroups, other users that are not admin can see it as well. Marie craeted a custom group called `marieCreated` and parhamoc2 can see it in list.
![image](https://github.com/SURFnet/rd-sram-integration/assets/25672014/61e49331-9b48-4025-9ef3-dfd3f886f0b0)

2- Custom groups are not showing in the group lists. Only one that is created by the configuration file is showing (not sure if we have bugfix here).
![image](https://github.com/SURFnet/rd-sram-integration/assets/25672014/b37aa782-f041-4508-a67d-e82f81c47af8)
![image](https://github.com/SURFnet/rd-sram-integration/assets/25672014/eea223f5-436e-449e-9dad-14a2632f513a)

**Comment by thepeak99** [comment]
To be addressed by #199 and https://github.com/pondersource/oc-opencloudmesh/issues/4

**Comment by parhamin2010** [comment]
# New items
1- On SCIM Controller we cannot add new rows to members
2- I did this scenario and result is not good :)

- create two new users on oc1 and oc2.
- on oc1 I added parhamoc1 and oc2 I added parhamoc2.
- I run [createGroup endpoint](https://github.com/SURFnet/rd-sram-integration/blob/mix-provider/ScimControllerDocs.md#creategroup) and got result as it should be `{"status":"success","message":null,"data":{"members":[{"value":"parhamoc1@oc1.docker","ref":"","displayName":"parhamoc1"},{"value":"marie@oc2.docker","ref":"","displayName":"marie@oc2.docker"}]}}` 
- I shared a new file from oc1 named testFromOc1 with that Group 
![image](https://github.com/SURFnet/rd-sram-integration/assets/25672014/c4d8479d-d904-4213-b0ee-ccac47bdc6f1)
- login with marie@oc2.docker and **no popup for file share show up**
![image](https://github.com/SURFnet/rd-sram-integration/assets/25672014/2f8574dd-d9f9-4472-9499-58468447dbe5)

**Comment by navid-shokri** [comment]
* I did not get the meaning of the first Item. You can add users to an existing group by updating the group. Please send more detail if it does not work.
* did you make Marie a member of your newly added group in oc2?
