### ISSUE TITLE
Using our opencloudmesh app: when a user on oc1.docker shares a file to a group on oc2.docker, then recipients on oc2 still see the 'Accept?' dialog, despite 'automatically accept' setting

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#209]
Apparently the 'automatically accept federated shares' setting has no effect, as reported by @navid-shokri in https://github.com/SURFnet/rd-sram-integration/issues/205#issuecomment-1602076938

I'll have a look.

**Comment by shokri-navid** [comment]
So, federated file sharing was implemented just for federated users so, it should be normal if it does not have any affect on federated groups.

**Comment by michielbdejong** [comment]
Yes, it's normal that it's broken if we don't fix it, but that doesn't mean we shouldn't fix it. :)

I'm updating the title btw assuming that this same behaviour also happens if you have only the opencloudmesh app, so then the federatedgroups app is unrelated here, and assigning milestone 1.1.

**Comment by michielbdejong** [comment]
Duplicate of #53
