### ISSUE TITLE
Not clear which owncloud/core branch to use

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#210]
In dev-stock we're using `ocm-cleaning`: https://github.com/pondersource/dev-stock/blob/3fcf168/scripts/init-rd-sram.sh#L7 
But https://github.com/owncloud/core/pull/40589 uses the `accept-ocm-to-groups` branch.

Which one is correct?

**Comment by navid-shokri** [comment]
So we are using this `oc-opencloudmesh-testing` branch to build and create our testing environment. I mentioned it in this part of the documentation.
https://github.com/SURFnet/rd-sram-integration#testing-environment

**Comment by michielbdejong** [comment]
@navid-shokri thanks for reporting that apart from unclarity about which branch of `owncloud/core` to use, there is also unclarity about which branch of `dev-stock to use, let's fix that!

I'm not creating a separate break-out issue about this, because the answer is pretty simple:

**We should all be using the`main` branch of `dev-stock`, always.**

For this issue in the context of milestone 1.2, see #211 
For this issue in the context of milestone 1.1, I already updated the docs (testing this myself now) - https://github.com/pondersource/oc-opencloudmesh/commit/ab0c0a830f2a2119113db092c39f375c42f32736

So OP question remains:
* which branch of `owncloud/core` should we use in combination with our opencloudmesh app and/or in combination with our opencloudmesh + federatedgroups apps?

**Comment by navid-shokri** [comment]
So, we were working on `oc-opencloudmesh-testing` branch of the dev-stock from the beginning of that. I can remember you told us to use that branch and there was no newer update for us. so we continued using mentioned branch until now. 

according to the this (file)[https://github.com/pondersource/dev-stock/blob/oc-opencloudmesh-testing/scripts/init-rd-sram.sh]

we are using these branches for each repository: 
1- owncloud core --> accept-ocm-to-groups
2- rd-sram (federated groups) --> main 
3- oc-opencloudmesh --> main 

I used this and it seems it was updated and functional for our development. 
If we **Should** using the main branch it was not told to me at least and so I documented my process and let others review my documentation and no one was raise any claim. So It seems all of us were on the same page except you.

**Comment by thepeak99** [comment]
Ok so lets leave dev-stock for a second, let's find out what are the differences between `ocm-cleaning` and `accept-ocm-to-groups` and merge them into one. @navid-shokri

**Comment by michielbdejong** [comment]
OK in the meantime I'll test to what extent Yashar's app works with the current state of `accept-ocm-to-groups`

**Comment by michielbdejong** [comment]
We're not fully on `accept-ocm-to-groups`.

If you find anything missing from that branch then you can add it there, but for now it seems to be mostly working.
