### ISSUE TITLE
Autocomplete of normale groups/users broken

### ISSUE THREAD

**Issue by T0mWz** [SURFnet/rd-sram-integration#218]
When OpenCloudMesh and FederatedGroups are enable, autocomplete doesn't work anymore.

Behaviour before enabling;
![Screenshot 2023-07-03 at 13 08 02](https://github.com/SURFnet/rd-sram-integration/assets/2477797/e256b9e4-cdb6-4619-aa7e-03915548c425)

**Comment by T0mWz** [comment]
```
{"reqId":"ZKKr6qMLb9T9vhqp_aDxxgAAAAA","level":3,"time":"03\/Jul\/2023:13:07:23","remoteAddr":"10.234.0.14","user":"surfsara","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=Tom&perPage=200&itemType=folder","message":"Undefined index: exact at \/var\/www\/owncloud\/apps\/opencloudmesh\/lib\/ShareeSearchPlugin.php#209"}
{"reqId":"ZKKr6qMLb9T9vhqp_aDxxgAAAAA","level":3,"time":"03\/Jul\/2023:13:07:23","remoteAddr":"10.234.0.14","user":"surfsara","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=Tom&perPage=200&itemType=folder","message":"Trying to access array offset on value of type null at \/var\/www\/owncloud\/apps\/opencloudmesh\/lib\/ShareeSearchPlugin.php#209"}
```

**Comment by navid-shokri** [comment]
@T0mWz can you provide your searched phrase or more details?

**Comment by T0mWz** [comment]
> @T0mWz can you provide your searched phrase or more details?

I don't get your point?
Just try to share with a user or group, then the autocomplete function is broken. See error above.

**Comment by navid-shokri** [comment]
So, You asked about the reason for two different results(Federated, Federated Groups) in the share search textbox and I assume that was working on your environment. So, this question was totally a surprise for me.

**Comment by navid-shokri** [comment]
I test it in our rd-sram testing environment and it is the result

![image](https://github.com/SURFnet/rd-sram-integration/assets/123634558/0162e7ed-373b-4b61-b341-efab1a7e7ae3)

**Comment by T0mWz** [comment]
> So, You asked about the reason for two different results(Federated, Federated Groups) in the share search textbox and I assume that was working on your environment. So, this question was totally a surprise for me. If there are some changes or specific conditions could help us.

Let's discuss that in that issue, please? 
https://github.com/SURFnet/rd-sram-integration/issues/219
