### ISSUE TITLE
cannot create a mountpoint for share

### ISSUE THREAD

**Issue by soltanireza65** [SURFnet/rd-sram-integration#224]
related to #53 
we need these steps to create a mount point for a share:
```php
$shareFolder = Helper::getShareFolder();
$mountPoint = Files::buildNotExistingFileName($shareFolder, $name);
$mountPoint = Filesystem::normalizePath($mountPoint);
$hash = \md5($mountPoint);
```

at first ` Helper::getShareFolder();` raise an error as `Call to a member function file_exists() on null`

first trace: we need to call `\OC_Util::setupFS($user);`
but we still have the same error

**Comment by navid-shokri** [comment]
Does it mean setupFS does not call the fileSystem::init()? or it calls but there is some failure?

**Comment by soltanireza65** [comment]
I did not trace it through the code yet, but it should call at least once (because its singleton)
I need to trace the code to be sure

**Comment by soltanireza65** [comment]
as a short answer we can not call setupFS for non loged-in users
