### ISSUE TITLE
oc_uc_fg_group_user: not found

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#235]
split out from #234

**Comment by michielbdejong** [comment]
Trying to reproduce this by running
https://github.com/pondersource/dev-stock/blob/415b275/scripts/testing-rd-sram.sh#L84
interactively

**Comment by michielbdejong** [comment]
Trying to see what happens if i comment out https://github.com/SURFnet/rd-sram-integration/blame/490d554/federatedgroups/appinfo/Migrations/Version20230523140843.php#L42-L45

**Comment by soltanireza65** [comment]
@michielbdejong 
![image](https://github.com/SURFnet/rd-sram-integration/assets/53468377/3dba3e9f-4a3f-40e5-86ea-cfba4ef99e21)
These are the tables when running `bootstrap_rd_sram`

**Comment by soltanireza65** [comment]
{$prefix}uc_fg_group_user
This is the unique index for `user and group` combination we made when Tom asked for it

**Comment by soltanireza65** [comment]
![image](https://github.com/SURFnet/rd-sram-integration/assets/53468377/50c0d8cf-f044-4ad1-9ec0-08568d0b3d03)

**Comment by michielbdejong** [comment]
@soltanireza65 sorry to hear you couldn't reproduce this bug, let's try together!

**Comment by michielbdejong** [comment]
Conclusion: Reza wasn't trying to reproduce this issue, he was just trying to find the underlying truth or falsehood of the content of the error message.
So now our setup script reproducibly prints an error, but we think it can be safely ignored.
Reza will try to dig into it more.

**Comment by michielbdejong** [comment]
On Tom's system the error message looks slightly different:
```
[root@255d201065ce owncloud]# sudo -u apache php occ app:enable federatedgroups
sh: line 1: oc_uc_fg_group_user: command not found
federatedgroups enabled
```

I've been digging into the occ command and it goes through 
https://github.com/owncloud/core/tree/master/lib/private/Console to https://github.com/doctrine/dbal/blob/aadddd5/src/Schema/Table.php#L225
and I can't see any shell execution or string 'not found' anywhere..


Aaah, I understand now! it's because of the backticks - when executing the php script using a shebang line like https://github.com/owncloud/core/blob/master/occ#L1 then ultimately the shell execution will evaluate those backticks as https://unix.stackexchange.com/questions/27428/what-does-backquote-backtick-mean-in-commands

So let's replace it with `"` and try again! :)
