### ISSUE TITLE
occ command broken by optional step 6

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#237]

**Comment by michielbdejong** [comment]
if you run the optional step 6 of https://github.com/SURFnet/rd-sram-integration#instruction then you will have this error when running the occ command in one of the OC containers:
```
$ docker exec -it -u www-data oc1.docker ./occ asdf
PHP Notice:  Undefined index: HTTP_HOST in /var/www/html/config/config.php on line 14
[...]
```

**Comment by soltanireza65** [comment]
I was able to reproduce the issue

**Comment by soltanireza65** [comment]
https://github.com/SURFnet/rd-sram-integration/pull/238

**Comment by michielbdejong** [comment]
one possible solution might be something like`3 => (isset(\$_SERVER['HTTP_HOST']) ? \$_SERVER['HTTP_HOST'] : 'localhost')`

**Comment by michielbdejong** [comment]
another option might be something like
```
sed ... 3 => "`hostname`"
```
