### ISSUE TITLE
Error on loading owncloud.

### ISSUE THREAD

**Issue by navid-dada** [SURFnet/rd-sram-integration#24]
I am getting this error when I am trying to load `oc1.cloud`.
` {"reqId":"aka1bbnvKPLbbpF58xuP","level":3,"time":"2022-11-09T13:59:37+00:00","remoteAddr":"172.20.0.6","user":"--","app":"no app in context","method":"POST","url":"\/index.php\/heartbeat","message":"Exception: {\"Exception\":\"OCP\\\\App\\\\AppNotFoundException\",\"Message\":\" does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/App\\\/AppManager.php(504): OC\\\\App\\\\InfoParser->parse()\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/App\\\/AppManager.php(797): OC\\\\App\\\\AppManager->getAppInfoByPath()\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/App\\\/AppManager.php(738): OC\\\\App\\\\AppManager->getAppVersionByPath()\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/App\\\/AppManager.php(680): OC\\\\App\\\\AppManager->findAppInDirectories()\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/app.php(558): OC\\\\App\\\\AppManager->getAppPath()\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/app.php(115): OC_App::getAppPath()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(591): OC_App::loadApps()\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(1060): OC::init()\\n#8 \\\/var\\\/www\\\/html\\\/index.php(53): require_once('\\\/var\\\/www\\\/html\\\/l...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/App\\\/InfoParser.php\",\"Line\":41}"}`

I am running the container using ./start-testnet.sh

**Comment by navid-dada** [comment]
I ran it by `./scripts/start-testnet.sh`  but the result is similar to before.

**Comment by michielbdejong** [comment]
@navid-dada can this be closed?

**Comment by michielbdejong** [comment]
I think this was resolved with the move to GitHub Codespaces, please reopen if this error reoccurs.
