### ISSUE TITLE
User cannot see the files that are shared with their group. 

### ISSUE THREAD

**Issue by navid-dada** [SURFnet/rd-sram-integration#28]
I share a file from oc1.docker with a group on oc2.docker.
on oc1 file marked as shared with a group on oc2. docker and also a record had been inserted into oc_share_external table of maria2.docker.

but Marie cannot see the file inside her file browser in the  `shared with you` category.

**Comment by navid-dada** [comment]
it seems that the current share manager just retrieves the shared file according to the username. but we should add the group criteria to that method.

**Comment by navid-dada** [comment]
The starting point is the Share20OcsController.php --> getShares function of the files_shareing app

**Comment by navid-dada** [comment]
call hierarchy is : 

1- Share20OcsController.php --> getShares()
2- Share20OcsController.php -->getSharedWithMe()
3- Share20 --> Manager --> getSharedWith()

**Comment by navid-dada** [comment]
at this line: 
https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/lib/private/Share20/Manager.php#L1360

$provider is instantiated from https://github.com/SURFnet/rd-sram-integration/blob/main/federatedgroups/lib/GroupShareProvider.php

and because it is inherited from DefaultShareProvider without overriding the `getSharedWith` method it is acting like the parent.

**Comment by navid-dada** [comment]
I encountered with a important question. If we query shared file based on group name the first user who accept the shared file flag it as accepted for all the group member. so it is dictatorship approach :) that we are familiar with in Iran :(. 
solution that is acceptable is add share file for all the users those are member of the given group. we also should listen to `User Added to / Removed from Group` events.

**Comment by navid-dada** [comment]
next challenge is finding a way to distinguish between `user id` and `group Id` when we are accepting/rejecting shred file.

**Comment by navid-dada** [comment]
So if the current behavior (auto accepting) is desired so there is no need to listen to any event anymore.

**Comment by navid-dada** [comment]
so there are a lot of changes that we should perform on : [Manager.php](https://github.com/pondersource/core/blob/master/apps/files_sharing/lib/External/Manager.php)
 to check the given user Id is really an user Id or it is group id actually

**Comment by navid-dada** [comment]
> the first user who accepts the shared file flag it as acceptable for all the group members.
the same problem is valid for deleting the shared file. if I cannot remove a group shared file independently without affecting other users.

**Comment by navid-dada** [comment]
I did not find any function in the owncloud's sdk to add and accept share meanwhile. I should take a look at custom group code. but as it is understood it is just available for the SaaS and Enterprise version.

**Comment by michielbdejong** [comment]
No, it's an app, we're already using it:
https://github.com/SURFnet/rd-sram-integration/blob/ba45efc/scripts/start-testnet.sh#L61
Do you see this group in your Codespace?

**Comment by navid-dada** [comment]
So I checked the custom group behavior. 
I found multiple point about it: 

1- It does not work with   `FederatedGroup/ShareProviderFactory.php`
2 - if we disable settings > sharing >  ` Automatically accept new incoming local user shares ` workflow will add a row in `oc_share` for each user who disabled this option. and also a row for whole group.
3- ... will update

**Comment by michielbdejong** [comment]
I think maybe in https://github.com/pondersource/core/blob/95792e6/apps/federatedfilesharing/lib/Controller/OcmController.php#L239 we need to check the group name with `customgroup_` prefix? Let's debug! :)

**Comment by navid-dada** [comment]
I changed the approach. every incoming federated group share will add an oc_file_external share entry for each group member user. so this resolves the problem and all functionalities are working correctly without any new changes in other places.

**Comment by michielbdejong** [comment]
> I changed the approach. every incoming federated group share will add an oc_file_external share entry for each group member user.

Hm, but that's different from how it works for local group shares, as you described in https://github.com/SURFnet/rd-sram-integration/issues/28#issuecomment-1335193283

> so this resolves the problem

What is "the problem"? Are you referring to your earlier question?

> what if all group set option true and one of them delete that file.
> this comment will be updated

I don't know if it's possible to delete a file that was shared with you. Let's try it!
Also, is it possible to revoke a share if it came to you as a local group share?

Can we make external group shares work the same way as local group shares?
Maybe this is a question to discuss with Juan.

**Comment by michielbdejong** [comment]
Progress:
* [commits](https://github.com/pondersource/core/commits/accept-ocm-to-groups)
* [code](https://github.com/pondersource/core/blob/73c52b526198d0f7673d0e3425a0fe7cace94f7a/apps/federatedfilesharing/lib/Controller/OcmController.php#L245)

**Comment by michielbdejong** [comment]
Leaving this issue closed as a duplicate of #14.
