### ISSUE TITLE
remove share on receiving side if sender revokes it

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#35]

**Comment by thepeak99** [comment]
Unit tests and integration tests required in both apps.

**Comment by michielbdejong** [comment]
For the OCM app, see #75

**Comment by navid-shokri** [comment]
I found that we cannot use Gerkin and Behat in our app and we should use it inside Owncloud core.
at least I never saw any application that has an acceptance test in it.
So, I decided to create some functional test and unit test to test this functionality.

**Comment by navid-shokri** [comment]
So there are two merge requests in separate repositories.
https://github.com/SURFnet/rd-sram-integration/pull/227/files
https://github.com/pondersource/oc-opencloudmesh/pull/40

I added more test cases to ensure functionality.
Also, I will attach a screencast to make show the functionality is working perfectly.

**Comment by navid-shokri** [comment]
https://github.com/SURFnet/rd-sram-integration/assets/123634558/4cc85677-7a22-477e-94e7-3802b900a538
