### ISSUE TITLE
How should we decide about share type in sender party?

### ISSUE THREAD

**Issue by navid-dada** [SURFnet/rd-sram-integration#36]
at the meeting that we have with Juan, we comprehend that there is a share type  in create share function in 
https://github.com/owncloud/core/blob/24c01cf8435fbce51530aca98928cfa0ed0e78db/apps/federatedfilesharing/lib/Controller/OcmController.php#L167

so it indicates that we should send the sharetype parameter from the sender side. so we should find out a way to determine the share type based on the sharee address.

**Comment by navid-dada** [comment]
the shared type is decided by the query itself.
when you are trying to search a group or user inside the share search textbox it sends a query to the server and the server search for all share provider to find the appropriate result. in each item in the result list, there is a share type value according to this predefined values. 

https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/lib/private/Share/Constants.php#L27

**Comment by navid-dada** [comment]
if I create a `my_test` group on the oc2.docker server and search for it inside oc1.docker to share a file/folder with that the request and response of the search will be :

```
Request: 
[GET]	https://oc1.docker/ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json&search=my_test@oc2.docker&perPage=200&itemType=file
```
```
Response:

{
   "ocs":{
      "meta":{
         "status":"ok",
         "statuscode":100,
         "message":"OK",
         "totalitems":"",
         "itemsperpage":""
      },
      "data":{
         "exact":{
            "users":[
               
            ],
            "groups":[
               
            ],
            "remotes":[
               {
                  "label":"navid_test@oc2.docker",
                  "value":{
                     "shareType":6,
                     "shareWith":"navid_test@oc2.docker"
                  }
               }
            ]
         },
         "users":[
            
         ],
         "groups":[
            
         ],
         "remotes":[
            
         ]
      }
   }
}
```

So, the result indicates that the share controller interprets the result as a remote item.

**Comment by navid-dada** [comment]
please look at this line of code. It is setting 'user' as share_type inside the HTTP request to ask the receiver party to store sharing item info.

https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/apps/federatedfilesharing/lib/Notifications.php#L411

**Comment by navid-dada** [comment]
this is the sequence of API calls on the sender side:

1- https://github.com/pondersource/core/blob/master/apps/files_sharing/lib/Controller/Share20OcsController.php#L370

2- https://github.com/pondersource/core/blob/master/lib/private/Share20/Manager.php#L716

3- https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/lib/private/Share20/Manager.php#L821

4 - https://github.com/pondersource/core/blob/master/apps/federatedfilesharing/lib/FederatedShareProvider.php#L143

5- https://github.com/pondersource/core/blob/master/apps/federatedfilesharing/lib/FederatedShareProvider.php#L220

6- https://github.com/pondersource/core/blob/master/lib/private/Share/Share.php#L2944

7- https://github.com/pondersource/core/blob/master/apps/federatedfilesharing/lib/Notifications.php#L402

**Comment by michielbdejong** [comment]
> the share controller interprets the result as a remote item

Well, I might be wrong but off the top of my head, the federated share provider checks if the last part of the search string looks like `@example.com`, if so it tries to fetch `https://example.com/ocm-provider` and if it looks like example.com accepts OCM shares, it proposes share type 6. So instead of "the *share controller* interprets the *result* as a remote *item*" I would say "the *federated share provider* interprets the *search string* as a remote *sharee*" - would you agree?

**Comment by michielbdejong** [comment]
> the share type is decided by the query itself. [...] in each item in the result list, there is a share type value

Yes! Not to be nit-picking, but the way I understand it, the query is the search string that the user enters, and the result list are the suggestions that get shown. So the share type is not decided by the query itself, but by the query *result*, right? Maybe this is what you meant.

**Comment by michielbdejong** [comment]
> please look at this line of code. It is setting 'user' as share_type

Yes. That's what ownCloud does on the sending side. So it has two shortcomings:
- it doesn't support receiving an OCM share to a group
- it also doesn't support *sending* an OCM share to a group

Good research, keep it up!

**Comment by navid-dada** [comment]
> > the share controller interprets the result as a remote item
> 
> Well, I might be wrong but off the top of my head, the federated share provider checks if the last part of the search string looks like `@example.com`, if so it tries to fetch `https://example.com/ocm-provider` and if it looks like example.com accepts OCM shares, it proposes share type 6. So instead of "the _share controller_ interprets the _result_ as a remote _item_" I would say "the _federated share provider_ interprets the _search string_ as a remote _sharee_" - would you agree?

so, It seems you are right and server do not search any external resources to enure about requested entity existence.

**Comment by navid-dada** [comment]
> > we should find out a way to determine the share type based on the sharee address.
> 
> Yes! That would be nice. But I don't know if it's possible? I therefore see two options:
> 
>     * always offer both 'remote group' and 'remote user' as hits on a search string that is "[something@some-ocm-provider.com](mailto:something@some-ocm-provider.com)"
> 
>     * check how Nextcloud does it (I think I proposed this already?)

So next cloud has a mechanism named search plugin as you can see. 
https://github.com/nextcloud/server/blob/0619207f13792250aea775a2c3133d41ab625980/lib/private/Collaboration/Collaborators/Search.php#L69
and there is a interface name `ISearchPlugin`  with multiple implementation but I think these two item are the most related items in the list: 
 

- https://github.com/nextcloud/server/blob/0619207f13792250aea775a2c3133d41ab625980/lib/private/Collaboration/Collaborators/RemoteGroupPlugin.php

- https://github.com/nextcloud/server/blob/0619207f13792250aea775a2c3133d41ab625980/lib/private/Collaboration/Collaborators/RemotePlugin.php

**Comment by michielbdejong** [comment]
I'm looking into this, I can't see those code paths getting used on Nextcloud.
I do see that for incoming OCM shares, NC also hard-codes to type 'user': https://github.com/nextcloud/server/blob/v25.0.2/apps/federatedfilesharing/lib/Controller/RequestHandlerController.php#L160

**Comment by michielbdejong** [comment]
I traced it in Nextcloud:
* there is a list of share types to search sharees for, it's constructed [here](https://github.com/nextcloud/server/blob/v25.0.2/apps/files_sharing/lib/Controller/ShareesAPIController.php#L171-L193)
* For remote group, it asks whether to search for that, [here](https://github.com/nextcloud/server/blob/v25.0.2/apps/files_sharing/lib/Controller/ShareesAPIController.php#L411)
* The backend asks the provider, [here](https://github.com/nextcloud/server/blob/v25.0.2/apps/files_sharing/lib/ShareBackend/File.php#L199)
* The provider checks the app config db [here](https://github.com/nextcloud/server/blob/v25.0.2/apps/federatedfilesharing/lib/FederatedShareProvider.php#L1037).

**Comment by michielbdejong** [comment]
There is (still talking about Nextcloud here) a setting 'Allow users on this server to send shares to groups on other servers'
and a setting 'Allow users on this server to receive group shares from other servers'.
Both are unchecked by default.
<img width="1211" alt="Screenshot 2022-12-19 at 10 42 01" src="https://user-images.githubusercontent.com/408412/208395970-2f64842c-92f8-4221-b4e6-f71b276c6f9e.png">

**Comment by michielbdejong** [comment]
When I enable the checkbox, the GUI will now give 3 search results instead of 2 for something@somewhere.com:
* email
* OCM to user
* OCM to group

<img width="1211" alt="Screenshot 2022-12-19 at 10 44 36" src="https://user-images.githubusercontent.com/408412/208396347-30c293a8-0f09-47a2-b7ea-a84c8abfa0ad.png">


@navid-dada so that gives some context of how Nextcloud does it. I think we should we do the same in ownCloud:
When the 'Federated Groups' app is installed, an extra autocompletion shows up. Does that resolve this issue?
