### ISSUE TITLE
what is the process to share some file in local group?

### ISSUE THREAD

**Issue by navid-dada** [SURFnet/rd-sram-integration#37]
we need to check the process of local sharing to copy the on business layer and patch our database layer below it to modify the table that the Federated-group persist the shared files information.

**Comment by michielbdejong** [comment]
For reference:
The answer to this question in terms of GUI and database: that's what we tested and written down in https://github.com/SURFnet/rd-sram-integration/issues/18#issuecomment-1345610765

I guess this ticket is to write down which function calls and code snippets in which files are involved?

**Comment by navid-dada** [comment]
Yes, I create this issue to find out the business logic of group sharing in local:
 and the answer is there:
 
https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/apps/files_sharing/lib/Controller/Share20OcsController.php#L588

unfortunately, business is scattered across the multiple layer in own cloud and in this case   logic is written inside controller.
