### ISSUE TITLE
Add a search plugin for remote groups

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#41]
Similar to the existing search plugin for remote users, see #36

**Comment by michielbdejong** [comment]
This is needed for the send-to-remote-group flow.
It's essential to making this app useful to ownCloud in general.
However, SURF will probably not enable this functionality in Research Drive, because there we will only look at sharing with federated groups (that the groups backend on the sending server also knows about), not with remote groups (that only exist on the receiving server).

**Comment by navid-dada** [comment]
this line should be checked to find out where the remote items are added to search result.

https://github.com/pondersource/core/blob/2afcfcbccfd2b30fedc04b1df228bb08ee53e7ca/apps/files_sharing/lib/Controller/ShareesController.php#L486

**Comment by navid-dada** [comment]
I finished this task last night, in this commit. I added a `G_` prefix on the label SHARE_TYPE_REMOTE_GROUP temporarily. 
so the result of the search will be like this: 

mysearch@mysite.com
G_mysearch@mysite.com

**Comment by michielbdejong** [comment]
Great work!
I think it's justified to return both the remote-user and the remote-group hit from the same function (instead of adding a separate function), since they work in exactly the same way.
I do think we need to add a checkbox in settings where the server admin can enable / disable the option to allow users to share to remote groups, same as what Nextcloud has.
Also, maybe we could add a nice icon in the search result instead of the `G_` prefix which you added temporarily now.
But apart from that, this really shows how it can work, awesome!

**Comment by michielbdejong** [comment]
> I finished this task last night, in this commit.

I think you forgot to include the link; did you mean [this commit](https://github.com/pondersource/core/commit/7236aaa38e0c977609818cb076f163dff3f5a301)?

**Comment by navid-dada** [comment]
yes, you are right. I edited my comment and added the link. :+1:
