### ISSUE TITLE
how to find out the @ is for email or is for federated enquery?

### ISSUE THREAD

**Issue by navid-dada** [SURFnet/rd-sram-integration#44]
this link of code can be helpful.

https://github.com/pondersource/core/blob/754bf5a85b25b3f45b8d27b74c7ad7f24818d345/apps/files_sharing/lib/Controller/ShareesController.php#L559

**Comment by michielbdejong** [comment]
it depends on the search type! 
https://github.com/pondersource/core/blob/754bf5a85b25b3f45b8d27b74c7ad7f24818d345/apps/files_sharing/lib/Controller/ShareesController.php#L252 will return hits of type user for email addresses that appear in the user's addressbook.

I don't see any code in ownCloud that will return hits for type email but in Nextcloud there is https://github.com/nextcloud/server/blob/04b2803e024d5cb04bb122becad66026aaa4572a/lib/private/Collaboration/Collaborators/MailPlugin.php#L262 which I think will return a hit for share type email whenever the search string is a valid email address.

Regarding whether a search string that contains an 'something@domain.com' is a valid OCM address (user or group), it will do a call to https://domain.com/ocm-provider and get back some JSON that shows that domain.com is capable of receiving OCM shares. If so, then  'something@domain.com' will be a hit for OCM share to user and (if supported and enabled) also for OCM share to group.

**Comment by michielbdejong** [comment]
I think I still don't understand the question. If the question is how does the server code distinguish local from remote users, then the answer is, [it looks at the `#` separator](https://github.com/SURFnet/rd-sram-integration/blob/75d7d95/federatedgroups/lib/GroupShareProvider.php#L162).

**Comment by michielbdejong** [comment]
So is this issue about strings that come from the group manager, or about strings that show up in the autocomplete dropdown?

**Comment by michielbdejong** [comment]
If it's about the autocomplete dropdown in the 'share with' GUI, then the answer is:
* there are icons and extra strings, like a little envelop indicating "email", or the word "Federated" appearing in the div.
* you added G_ to the hit for a remote group. we should replace this with the 'group' icon that Nextcloud has for this.

**Comment by michielbdejong** [comment]
Ah, you're talking about how to address a remote user in OCM if the remote username has an @ symbol in it.
Answer: I think this is not supported in OCM.

**Comment by michielbdejong** [comment]
After #55 we'll store for instance `federalists#oc2.docker` as a string in `oc_group_user`.
IIUC you are suggesting to use `federalists@oc2.docker` instead.
I think the current implementation is better than your suggestion because it provides a context-free way of determining whether a group member is local or foreign, and yours doesn't. What is the advantage of your suggestion?

**Comment by michielbdejong** [comment]
There is no `@` sign in the query to the groups backend.

**Comment by navid-dada** [comment]
I finally understand what is # for. we use # because when we query a group on the federated group manager, it will return its users and their host address. # mimic that these users are comeing from federated group manager.
