### ISSUE TITLE
Insert incoming group shares into external_share_group table.

### ISSUE THREAD

**Issue by navid-dada** [SURFnet/rd-sram-integration#46]
currently the existing code is working with oc_share_external table and it sends its queries and commands on mentioned table.
we should change these codes and refer to share_external_group table to manipulate the group shares.

**Comment by navid-dada** [comment]
The first step is to check whether the incoming share is duplicate or not. 

FederatedShareProvider -> getShareWith.

**Comment by navid-dada** [comment]
there are two methods to check existing shares:

1- getShareWith()
2- getShareFromExternalShareTable()

in the existing workflow when the first one has a result our request will throw this exception: **` Sharing %s failed because this item is already shared with %s`**
and when the second one has a result it will try to add a new row in the database and ask the file owner to ensure resharing.

so, there we are faced with this question. 
in the new workflow should we check the external shared file and if there was any result we throw a duplicate share exception and substitute checking share_external_group with the second item?

**Comment by navid-dada** [comment]
It is done by this approach.
we will add one row for the group entry  `7` for the value of the share_type column. and one row for each member of the group with a filled parent column with the Id of inserted row for group entry and `6` for the share_type column.

**Comment by navid-dada** [comment]
done of this issue is dependent on:
 https://github.com/SURFnet/rd-sram-integration/issues/47

**Comment by michielbdejong** [comment]
Done
