### ISSUE TITLE
change the logic to indicate that incoming group type share is automatically accepted or not?

### ISSUE THREAD

**Issue by navid-dada** [SURFnet/rd-sram-integration#47]
there is a function call that indicates whether the auto-accept for incoming OCM share to the user file sharing is checked or not. the logic currently belongs to federated sharing. 
we should make a decision about this function.  is it required and if the answer is 'YES' how we should implement that?

**Comment by michielbdejong** [comment]
can you provide some links?
> there is a function call that indicates whether the auto-accept remote group file sharing is checked or not. 

is that code you wrote?

**Comment by navid-dada** [comment]
https://github.com/SURFnet/rd-sram-integration/blob/9afb7bfce1feeeb414fb4fb982a15ac2a29d7c63/federatedgroups/lib/FederatedShareProvider.php#L1184

**Comment by michielbdejong** [comment]
> there is a function call that indicates whether the auto-accept for incoming OCM share to the user file sharing is checked or not.

Right, that makes sense, because there is a checkbox for this in the settings. I think it's different for trusted vs non-trusted servers, right?

**Comment by michielbdejong** [comment]
My understanding of this function is:

it returns whether all of the following are true:
* auto accept shares from trusted servers is set to true at the server level (`auto_accept_trusted` config entry)
* auto accept shares from trusted servers is set to true at the user level(`auto_accept_share_trusted` config entry)
* the server in question (from which the share came) is trusted
* something with `autoAddServers` which we don't understand.

It seems that this function actually dispatches a `remoteshare.received` event every time it's called, and it definitely seems that it's not a function that does what its name suggests (which would be probably to read whether the current share was accepted by the current user)

**Comment by michielbdejong** [comment]
> the logic currently belongs to federated sharing

As discussed, by that you mean that it is in the FederatedShareProvider class, which we copied from the federatedfilesharing app to our app.

**Comment by michielbdejong** [comment]
> is it required

we don't fully understand what it does, so we should look at how and where it's called.

The behaviour for auto-accepting OCM shares to group will probably have to be a mix between the behaviour for auto-accepting OCM shares to user and the behaviour for auto-accepting shares to local groups. Didn't we take a product decision about this yet?

**Comment by michielbdejong** [comment]
The desired behaviour is as described in #50.

**Comment by michielbdejong** [comment]
Ah, the function name makes more sense if you look at
https://github.com/owncloud/core/blob/f4026550953eb3cc468d9d5b1c2d25a0503d40c9/apps/federatedfilesharing/lib/FederatedShareProvider.php#L1133
and
https://github.com/owncloud/core/blob/f4026550953eb3cc468d9d5b1c2d25a0503d40c9/apps/files_sharing/lib/External/Manager.php#L113

It means "get the value that we should record for the "accepted" attribute of the newly created share in the oc_share_external table.

**Comment by michielbdejong** [comment]
So basically we want the same behaviour for auto-accept, regardless of whether a share arrives at you as an OCM share to user or an OCM share to group of which you are a member.

**Comment by michielbdejong** [comment]
As discussed and documented in https://github.com/SURFnet/rd-sram-integration/issues/50#issuecomment-1367808646 , the answer is yes, and auto-accept logic for groups should be as you already implemented it in https://github.com/SURFnet/rd-sram-integration/blob/9afb7bfce1feeeb414fb4fb982a15ac2a29d7c63/federatedgroups/lib/External/Manager.php#L154 - analogous to https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/apps/files_sharing/lib/Controller/Share20OcsController.php#L591 but slightly different :)
