### ISSUE TITLE
List the OCM-to-group-shared items inside the "shared with me" category in the Files application. 

### ISSUE THREAD

**Issue by navid-dada** [SURFnet/rd-sram-integration#48]

**Comment by navid-dada** [comment]
I implemented this part and currently, ExternalShares API returns group shared Items for logged-in users but the file is not shown in the file GUI, 
GUI is showing a dialog to add einstein@oc1.docker into trusted servers each time we refresh the page.

**Comment by navid-dada** [comment]
## !!!BIG PROBLEM!!!

clicking on `Add federated share` button sends a POST request to this end point with just only Id of shared or pending Item. 
https://oc2.docker/index.php/apps/files_sharing/api/externalShares
it is just sending this simple body:
```Form-body = id:8```

**Comment by navid-dada** [comment]
so as you can see there is no type to indicate that shared file is `user` type or `group` type. and we should add this flag to select which workflow should be process to accept the shared file.

**Comment by navid-dada** [comment]
I found the place of the dialog manipulation code. and it seems we should change the body of HTTP POST request there. 
https://github.com/pondersource/core/blob/0cff1ab76857182f38c4259c94059e2888ea8586/apps/files_sharing/js/external.js#L133

**Comment by navid-dada** [comment]
this issue is splited to these issues #57 and #58

**Comment by navid-dada** [comment]
The Issues mentioned above have been closed but the shared file still is not visible in the files application. :

**Comment by navid-dada** [comment]
I guess we should check the `dav` provider of the Owncloud and change it to retrieve all shared files including federated group shared files.

**Comment by navid-dada** [comment]
I tried to share a file with the federated users to understand the workflow. but I am encountering this error when I accept the sharing:

```{"reqId":"1pCMwlRUnxa1n72yJUQx","level":3,"time":"2023-01-18T06:14:01+00:00","remoteAddr":"172.19.0.2","user":"behrad","app":"PHP","method":"POST","url":"\/index.php\/apps\/files_sharing\/api\/externalShares","message":"Undefined index: password at \/var\/www\/html\/apps\/files_sharing\/lib\/External\/Storage.php#88"}
{"reqId":"1pCMwlRUnxa1n72yJUQx","level":3,"time":"2023-01-18T06:14:01+00:00","remoteAddr":"172.19.0.2","user":"behrad","app":"PHP","method":"POST","url":"\/index.php\/apps\/files_sharing\/api\/externalShares","message":"Undefined index: password at \/var\/www\/html\/apps\/files_sharing\/lib\/External\/Storage.php#88"}
{"reqId":"1pCMwlRUnxa1n72yJUQx","level":3,"time":"2023-01-18T06:14:01+00:00","remoteAddr":"172.19.0.2","user":"behrad","app":"index","method":"POST","url":"\/index.php\/apps\/files_sharing\/api\/externalShares","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ServerException\",\"Message\":\"Server error: `POST https:\\\/\\\/oc1.docker\\\/index.php\\\/apps\\\/federatedfilesharing\\\/notifications` resulted in a `500 Internal Server Error` response:\\n{\\\"message\\\":\\\"internal server error, was not able to process notification\\\"}\\n\",\"Code\":500,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Middleware.php(69): GuzzleHttp\\\\Exception\\\\RequestException::create()\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(204): GuzzleHttp\\\\Middleware::GuzzleHttp\\\\{closure}(*** sensitive parameters replaced ***)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(153): GuzzleHttp\\\\Promise\\\\Promise::callHandler()\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/guzzlehttp\\\/promises\\\/src\\\/TaskQueue.php(48): GuzzleHttp\\\\Promise\\\\Promise::GuzzleHttp\\\\Promise\\\\{closure}(*** sensitive parameters replaced ***)\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(248): GuzzleHttp\\\\Promise\\\\TaskQueue->run()\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(224): GuzzleHttp\\\\Promise\\\\Promise->invokeWaitFn()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(269): GuzzleHttp\\\\Promise\\\\Promise->waitIfPending()\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(226): GuzzleHttp\\\\Promise\\\\Promise->invokeWaitList()\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(62): GuzzleHttp\\\\Promise\\\\Promise->waitIfPending()\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(187): GuzzleHttp\\\\Promise\\\\Promise->wait()\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/ClientTrait.php(95): GuzzleHttp\\\\Client->request()\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(247): GuzzleHttp\\\\Client->post()\\n#12 \\\/var\\\/www\\\/html\\\/apps\\\/federatedfilesharing\\\/lib\\\/Notifications.php(362): OC\\\\Http\\\\Client\\\\Client->post()\\n#13 \\\/var\\\/www\\\/html\\\/apps\\\/federatedfilesharing\\\/lib\\\/Notifications.php(278): OCA\\\\FederatedFileSharing\\\\Notifications->tryHttpPostToShareEndpoint()\\n#14 \\\/var\\\/www\\\/html\\\/apps\\\/federatedfilesharing\\\/lib\\\/Notifications.php(242): OCA\\\\FederatedFileSharing\\\\Notifications->sendUpdateToRemote()\\n#15 \\\/var\\\/www\\\/html\\\/apps\\\/federatedfilesharing\\\/lib\\\/AppInfo\\\/Application.php(255): OCA\\\\FederatedFileSharing\\\\Notifications->sendAcceptShare()\\n#16 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(264): OCA\\\\FederatedFileSharing\\\\AppInfo\\\\Application->OCA\\\\FederatedFileSharing\\\\AppInfo\\\\{closure}(*** sensitive parameters replaced ***)\\n#17 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(239): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->doDispatch()\\n#18 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(73): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->callListeners()\\n#19 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Manager.php(260): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->dispatch()\\n#20 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/Controllers\\\/ExternalSharesController.php(143): OCA\\\\Files_Sharing\\\\External\\\\Manager->acceptShare()\\n#21 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(170): OCA\\\\Files_Sharing\\\\Controllers\\\\ExternalSharesController->create()\\n#22 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#23 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#24 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#25 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#26 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(914): OC\\\\Route\\\\Router->match()\\n#27 \\\/var\\\/www\\\/html\\\/index.php(54): OC::handleRequest()\\n#28 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":113}"}```

**Comment by navid-dada** [comment]
there are multiple files in the External folder which look relevant. such as 
- `Mount.php`
- `MountProvider.php`
- `Storage.php`

I tried to debug the process but I had no success yet. but maybe we should adjust the duplicate files in the `federated groups` application.

**Comment by michielbdejong** [comment]
> Server error: `POST https:\\\/\\\/oc1.docker\\\/index.php\\\/apps\\\/federatedfilesharing\\\/notifications` resulted in a `500 Internal Server Error` response

Splitting this out to https://github.com/SURFnet/rd-sram-integration/issues/63

**Comment by navid-dada** [comment]
I rebuilt my environment and the second error line disappeared but the first one is raising. 

```{"reqId":"1pCMwlRUnxa1n72yJUQx","level":3,"time":"2023-01-18T06:14:01+00:00","remoteAddr":"172.19.0.2","user":"behrad","app":"PHP","method":"POST","url":"\/index.php\/apps\/files_sharing\/api\/externalShares","message":"Undefined index: password at \/var\/www\/html\/apps\/files_sharing\/lib\/External\/Storage.php#88"}```

this is the line that raises the error:

> https://github.com/SURFnet/rd-sram-integration/blob/2773f29442530ca167fc0b26323c5f5fb48f8d7b/federatedgroups/lib/External/Manager.php#L227

> https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/lib/private/Files/Mount/MountPoint.php#L142

> https://github.com/SURFnet/rd-sram-integration/blob/2773f29442530ca167fc0b26323c5f5fb48f8d7b/federatedgroups/lib/External/Storage.php#L82

**Comment by michielbdejong** [comment]
```
Undefined index: password at \/var\/www\/html\/apps\/files_sharing\/lib\/External\/Storage.php#88
```
What is on line 88 of that file inside the container that throws the error?

**Comment by navid-dada** [comment]
I marked it by an bold arrow
``` parent::__construct([
			'secure' => $secure,
			'host' => $host,
			// root will be adjusted lazily in init() with discovery manager
			'root' => $root,
			'user' => $options['token'],
			'password' => (string)$options['password'],  <<<<<<<<<<==========
			// Federated sharing always uses BASIC auth
			'authType' => Client::AUTH_BASIC
		])```

**Comment by navid-dada** [comment]
I just change that line to the `123` constant string to pass this step temporarily.  :warning:

**Comment by michielbdejong** [comment]
> GUI is showing a dialog to add the file from [einstein@oc1.docker](mailto:einstein@oc1.docker) each time we refresh the page.

That probably means that changing the state from pending to accepted was not successful

> there is no type to indicate that shared file is user type or group type in POST request.

You fixed this with #57 and #58

Other issues we've seen along the way were split out into #63 and #72.

Now continuing on the original issue. To reproduce this, make sure you are on the main branch of this repo,
Inside oc1/2.docker /var/www/html you may have to do a `git pull` to get the latest surf-dev branch of the core repo into the containers.

Then to reproduce:
* Einstein creates a folder 'asdf' and shares it with marie@oc2.docker
* Einstein creates a folder 'qwer' and shares it with helpdesk@oc2.docker
* Marie visits https://oc2.docker/index.php/apps/files/?dir=/&view=sharingin

Expected:
* Both asdf/ and qwer/ show up

Actual:
* Only asdf/ shows up

Screenshot:
![Screenshot 2023-01-30 at 11 34 49](https://user-images.githubusercontent.com/408412/215453693-415efe0f-e09a-4085-b38d-2b3b7894ac23.png)

**Comment by michielbdejong** [comment]
Hm, https://github.com/pondersource/core/blob/surf-dev/apps/files_sharing/lib/Controller/RemoteOcsController.php is unchanged from owncloud core master and so is https://github.com/pondersource/core/blob/surf-dev/apps/files_sharing/appinfo/routes.php#L108-L110 so I think I'm missing something. @navid-dada ?

**Comment by michielbdejong** [comment]
I was thinking maybe there was some code in [Navid's branch from December](https://github.com/pondersource/core/tree/2f055d1424a363ebb9622f7d0abddc7443470ed0/apps/files_sharing/lib/Controller) that we reverted but couldn't find any there either. I'll add an externalGroupManager to RemoteOcsController.

**Comment by michielbdejong** [comment]
![Screenshot 2023-01-30 at 16 16 25](https://user-images.githubusercontent.com/408412/215518753-81ef8950-d037-4d1a-b043-db431f50105b.png)
