### ISSUE TITLE
Which type should be set for group members entry on GroupRemoteSharing ?

### ISSUE THREAD

**Issue by navid-dada** [SURFnet/rd-sram-integration#49]
Currently we are adding 6 (remote) but in local sharing as You can see in below link: 
https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/lib/private/Share20/DefaultShareProvider.php#L421

this is Fill with '2' which is absent in this constant class: 

https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/lib/private/Share/Constants.php#L28

**Comment by michielbdejong** [comment]
As discussed, types 7 and 6 are fine.
