### ISSUE TITLE
product decision about auto-accept logic for receiving OCM shares to a group you're in

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#50]
inputs:
* does the current user have 'auto-accept shares to local groups' set to true?
* does the current user have 'auto-accept remote shares from trusted servers' set to true?
maybe we should require both?

**Comment by navid-dada** [comment]
![setting](https://user-images.githubusercontent.com/10582747/210052872-55317c60-6ea6-49f6-a16f-9de2861d5c9c.png)

**Comment by michielbdejong** [comment]
<img width="997" alt="Screenshot 2022-12-30 at 10 03 17" src="https://user-images.githubusercontent.com/408412/210053135-802343e2-2892-4a5d-90a9-0dee079eff62.png">

**Comment by michielbdejong** [comment]
Sorry, this one:
<img width="997" alt="Screenshot 2022-12-30 at 10 08 29" src="https://user-images.githubusercontent.com/408412/210053506-76c1771b-dbcc-4ef7-a0af-5bb5dbb2f31b.png">

**Comment by michielbdejong** [comment]
So before we auto-accept an incoming OCM share to group, we require:
* the sending server is trusted
* "Automatically accept federated shares from trusted servers" is ticked
* "Automatically accept new incoming local user shares" is ticked
* the group is not on the black list

**Comment by michielbdejong** [comment]
<img width="997" alt="Screenshot 2022-12-30 at 10 14 44" src="https://user-images.githubusercontent.com/408412/210053997-bd22fbe1-9c7e-474a-a9aa-c0922a559880.png">

**Comment by michielbdejong** [comment]
@navid-dada can you test the following:
* On oc2.docker, tick "Automatically accept federated shares from trusted servers"
* On oc2.docker, untick ""Automatically accept new incoming local user shares"
* share something from oc1.docker to a user on oc2.docker
* see if it's auto-accepted?

**Comment by navid-dada** [comment]
I do this and it is the process: 
I share a file with the mentioned condition without adding `oc1.docker` to the trusted server so the share will be in pending status.
but if I add oc1.docker to the trusted server it will be accepted automatically and listed as a completely shared file. 

Also, I checked another scenario, I delete oc1.docker from the trusted servers and ticked the ` Add server automatically once a federated share was created successfully ` and shared a file from oc1.docker to oc2.docker. it appeared as a pending share file but when I tried to accept that share 500 internal error has been raised. I make #51 to follow up.

**Comment by michielbdejong** [comment]
OK! So we're good, then. Decision taken! :) As per https://github.com/SURFnet/rd-sram-integration/issues/50#issuecomment-1367808646

**Comment by michielbdejong** [comment]
Granted, it's a bit weird that we're ignoring https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/apps/files_sharing/lib/Controller/Share20OcsController.php#L592 for incoming share to group, but then again, not much weirder than the behaviour that already exists as described in https://github.com/SURFnet/rd-sram-integration/issues/50#issuecomment-1367852820

**Comment by michielbdejong** [comment]
Let's leave this documented as a stretch goal -> https://github.com/SURFnet/rd-sram-integration/issues/53
