### ISSUE TITLE
500 internal error on accepting pending share and adding sender host as trusted host meanwhile.

### ISSUE THREAD

**Issue by navid-dada** [SURFnet/rd-sram-integration#51]
I delete oc1.docker from the trusted servers and ticked the `Add server automatically once a federated share was created successfully` and shared a file from oc1.docker to oc2.docker. it appeared as a pending share file but when I tried to accept that share 500 internal error has been raised

**_UPDATE_**

the file is accepted but a tooltip will appear that shows `500 internal error `

**Comment by navid-dada** [comment]
I looked at data/owncloud.log and found that I am getting this error when a shared request comes to the receiving server.
**Exception: HTTP\/1.1 400 Connection refused for URI https://oc1.docker/public.php/webdav**

**Comment by michielbdejong** [comment]
This seems fixed
