### ISSUE TITLE
Document code paths involved in the webdav mount

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#66]
Try to so an OCM-to-user of a folder (not a file) from einstein to marie, then see which code paths are used when Marie accesses the folder.

**Comment by navid-dada** [comment]
there is a function that may had some hint: 
https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/apps/federatedfilesharing/lib/Command/PollIncomingShares.php#L86
I checked it but it wasn't called :(

https://github.com/pondersource/core/blob/master/apps/files_sharing/lib/External/ScanExternalSharesJob.php
 also this was not called from outside.

**Comment by navid-dada** [comment]
Maybe this helps:
https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/apps/files_sharing/lib/AppInfo/Application.php#L200

**Comment by navid-shokri** [comment]
I tried to registerMountProvider in the app.php like that mentioned in the above comment. I was hoping this would help us to retrieve the shared by a remote group approach. but after all, it does not affect anything.

**Comment by navid-shokri** [comment]
I solve the problem "list the remote group shared files in the File application" by registering the mount provider and manager in `Application.php`.
