### ISSUE TITLE
what is ScanExternalSharesJob for? and how we should intract with it in our application?

### ISSUE THREAD

**Issue by shokri-navid** [SURFnet/rd-sram-integration#68]
https://github.com/pondersource/core/blob/master/apps/files_sharing/lib/External/ScanExternalSharesJob.php

**Comment by yasharpm** [comment]
The job scans received shares every 3 hours and updates their metadata. What happens as the result is that a few PROPFIND calls get file's size, mime type, modified time and such and updates the `filecache` table. It is safe and necessary for us to use this job for received shares on the `share_external_group` table.
