### ISSUE TITLE
It seems that new file structure is not acceptable for PHP autoload config.

### ISSUE THREAD

**Issue by navid-shokri** [SURFnet/rd-sram-integration#69]
I tried to test the application with the new file structure but I am encountering this error.

> Class 'OCA\\\\FederatedGroups\\\\Middleware\\\\OcmMiddleware' not found

> Class 'OCA\\FederatedGroups\\Notifications' not found 

>Class 'OCA\\FederatedGroups\\FederatedShareProvider' not found 

and this list is going on. I tried to resolve this problem by relocating the file to the main `lib`  folder, but it seems we should make a decision about this type of folder structure

**Comment by michielbdejong** [comment]
Yes sorry, I guess #62 was a bad idea!
We should use namespaces that match the folder structure.
And then it's not so nice to keep the "core/apps/" in there.
So maybe:
* move all of https://github.com/SURFnet/rd-sram-integration/tree/main/federatedgroups/lib/core/apps/federatedfilesharing to "lib/federated/" and call those classes names like 'OCA\FederatedGroups\Federated\ShareProvider'
* move https://github.com/SURFnet/rd-sram-integration/tree/main/federatedgroups/lib/core/apps/files_sharing/lib/External to "lib/sharing/External" and call those classes names like 'OCA\FederatedGroups\Sharing\External\MountProvider'

What do you think?

Any naming scheme that you can invent that is consistent for both the file paths and the class names is fine!

**Comment by michielbdejong** [comment]
So e.g.
* [apps/federatedfilesharing/lib/Middleware/OcmMiddleware.php](https://github.com/owncloud/core/blob/master/apps/federatedfilesharing/lib/Middleware/OcmMiddleware.php)
* OCA\FederatedFileSharing\Middleware\OcmMiddleware
* federatedgroups/lib/federatedfilesharing/Middleware/OcmMiddleware
* OCA\FederatedGroups\FederatedFileSharing\Middleware\OcmMiddleware

In general:

For classnames, OCA\X\A\B\C becomes OCA\FederatedGroups\X\A\B\C
For filepaths,

apps/X/lib/A/B/C becomes federatedgroups/lib/X/A/B/C

Where 'X' is either 'FederatedFileSharing' / 'federatedfilesharing' or 'FilesSharing' / 'files_sharing'

**Comment by michielbdejong** [comment]
Ah, looks like this was taken care of as part of https://github.com/SURFnet/rd-sram-integration/commit/cbba045899108e626238e27167c4dc58618f4033 - awesome!
