### ISSUE TITLE
adjust GUI for searching federated contacts.

### ISSUE THREAD

**Issue by navid-shokri** [SURFnet/rd-sram-integration#78]
in this picture, the `User` should be changed to `Federated Group` and the `G_` prefix should be removed.
it is more preferred to mark the results with some icon. 

![Screen Shot 2023-01-31 at 11 42 00 AM](https://user-images.githubusercontent.com/123634558/215703332-930416a4-1698-49eb-a559-3158705db043.png)

**Comment by soltanireza65** [comment]
the issue gets fixed in a hotfix branch in the core repo
https://github.com/pondersource/core/tree/hotfix/extendTypeInfo

the solution is to decide what to set as typeInfo based on the label property on each item
currently, the label is prefixed with "G_".

**Comment by soltanireza65** [comment]
it should be solved by setting the shareType to the "group" actually :  

as it has a corresponding case to check before

<img width="424" alt="Screen Shot 2023-01-31 at 10 01 06 PM" src="https://user-images.githubusercontent.com/53468377/215850709-c4c694d1-1cfc-4580-8580-a6c3f2c02044.png">

or extend the JS side

**Comment by michielbdejong** [comment]
Nice idea! But I do think I prefer an icon. See https://github.com/SURFnet/rd-sram-integration/issues/36#issuecomment-1357372082 for inspiration.

**Comment by soltanireza65** [comment]
Group Icon was added to the core and CSS applied
styled modified
OC javascript constants extended to support SHARE_TYPE_REMOTE_GROUP 
item template extended so that it accepts an icon conditionally

**Comment by navid-shokri** [comment]
So, can we change the status of this issue to Closed? @soltanireza65

**Comment by soltanireza65** [comment]
I think so
Removed G_ from shareDialogItem Response
file path: rd-sram-integration/federatedgroups/lib/ShareeSearchPlugin.php => line 95

**Comment by navid-shokri** [comment]
Well done @soltanireza65 
![image](https://user-images.githubusercontent.com/123634558/216306365-02e6f6dc-bd68-4449-80d0-735c969c468d.png)
