### ISSUE TITLE
typo in ShareeSearchPlugin.php

### ISSUE THREAD

**Issue by soltanireza65** [SURFnet/rd-sram-integration#82]
there is a logical issue in line 95 of this file that we are overriding the previous assay indexes in the loop
ovveral result is file though
but there is a miss conception there

<img width="385" alt="Screen Shot 2023-02-02 at 2 13 58 PM" src="https://user-images.githubusercontent.com/53468377/216303640-28afff23-3dbb-462b-abc6-93beab9420ff.png">

**Comment by michielbdejong** [comment]
Ah, weird! I thought that was working. I hope #83 fixes it!

**Comment by navid-shokri** [comment]
I guess it works in normal condition but as I and @soltanireza65 reviewed the code then it seems that we are replacing the first item with the second one. also, I think adding the Remote Group for already existing contacts is not a common and reasonable approach.

**Comment by navid-shokri** [comment]
> there is a logical issue in line 95 of this file that we are overriding the previous assay indexes in the loop ovveral result is file though but there is a miss conception there
> 
> <img alt="Screen Shot 2023-02-02 at 2 13 58 PM" width="385" src="https://user-images.githubusercontent.com/53468377/216303640-28afff23-3dbb-462b-abc6-93beab9420ff.png">

this problem is repeated in other blocks of the code.

**Comment by michielbdejong** [comment]
I think https://github.com/SURFnet/rd-sram-integration/commit/7d0f1daf2baa5856f485b2a5cf03a3f5301e02dc has something to do with it maybe?
