### ISSUE TITLE
In `Shared with me section` decline and Accept share buttons should send back share type to `RemoteOcs` controllers.

### ISSUE THREAD

**Issue by navid-shokri** [SURFnet/rd-sram-integration#85]
![image](https://user-images.githubusercontent.com/123634558/216541831-f54bdfb5-538d-46ed-bbf3-04359a52adcb.png)

**Comment by navid-shokri** [comment]
we should add another parameter to this function in js file.
https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/apps/files_sharing/js/app.js#L204

**Comment by soltanireza65** [comment]
there is no shareType in remote_shares response:

![Screen Shot 2023-02-05 at 11 30 48 PM](https://user-images.githubusercontent.com/53468377/216842026-538fc18f-904b-473d-bb38-3082ae7bc122.png)

**Comment by soltanireza65** [comment]
shareType added in _setShareState function signature.
https://github.com/pondersource/core/commit/7a65b7030effc6a9da234364ed435e7e4a5100fc

TODO: add it to controller

**Comment by soltanireza65** [comment]
@navid-shokri 
it now receives shareType as a POST property in the accept and decline routes in RemoteOcsController

https://github.com/pondersource/core/commit/810f3eb7d332d4766326bb55e367095c605ebe56?diff=split&w=1

**Comment by soltanireza65** [comment]
user-to-user share objects do not have a share type in response
scenario 1: share a file with marie@oc2.docker as einstein, Marie will not get "shareType" in the shares GET request for this share
scenario 2: share a file with helpdesk@oc2.docker as einstein, Marie will get "shareType" in the shares GET request for this share

**Comment by soltanireza65** [comment]
we should merge this PL to resolve this issue:
https://github.com/pondersource/core/pull/4
