### ISSUE TITLE
We use two different patterns: "shadow child" and "two managers in one controller". We should probably use just one.

### ISSUE THREAD

**Issue by soltanireza65** [SURFnet/rd-sram-integration#89]
https://github.com/pondersource/core/blob/7a65b7030effc6a9da234364ed435e7e4a5100fc/apps/files_sharing/lib/Controller/RemoteOcsController.php#L133

https://github.com/pondersource/core/blob/7a65b7030effc6a9da234364ed435e7e4a5100fc/apps/files_sharing/lib/Controllers/ExternalSharesController.php#L76

**Comment by soltanireza65** [comment]
we have two paths to go with:
1- to move https://github.com/pondersource/core/blob/fa9f0b40e8397f64cfc9682ea1b6bed916ae9c5d/apps/files_sharing/lib/Controller/RemoteOcsController.php#L149-L160 to the constructor, the trade-off is we must check if 'federatedgroups' is enabled right from the controller instantiation(even when we are not using getShares) and in getShares action(twise)
2- to use manager, instead of controller, in this case we would have duplicate controller action code in both

**Comment by navid-shokri** [comment]
so It seems that we should let it go and not change the code until we encountered with similar execution path determination,
After it, we could a more accurate decision. :information_source:

**Comment by michielbdejong** [comment]
The RemoteOcsController constructs a child of itself and then calls that from each function.
This pattern is what you call "to use controller".

The ExternalSharesController has 2 managers, 'externalManager' and 'groupExternalManager.
This pattern is what you call "to use manager".

**Comment by michielbdejong** [comment]
With "we would have duplicate controller action code in both" you mean that with pattern 2, the controller code has to be made aware of when to use which of its two managers.

**Comment by michielbdejong** [comment]
The reason you're comparing the two as "accessing the externalManager" is that the RemoteOcsController later (after going into its child or staying in the parent) [calls externalManager](https://github.com/pondersource/core/blob/fa9f0b40e8397f64cfc9682ea1b6bed916ae9c5d/apps/files_sharing/lib/Controller/RemoteOcsController.php#L163).

**Comment by michielbdejong** [comment]
I think we should use config variable as per https://github.com/SURFnet/rd-sram-integration/issues/117 wherever we are now using the "shadow child" pattern.
In places where we now use the "two managers in one controller" pattern, we can keep it as it is and see what the reviewers say.

**Comment by michielbdejong** [comment]
On a side note, https://github.com/pondersource/core/blob/7a65b7030effc6a9da234364ed435e7e4a5100fc/apps/files_sharing/lib/Controller/RemoteOcsController.php#L133 is passing https://github.com/pondersource/core/blob/7a65b7030effc6a9da234364ed435e7e4a5100fc/apps/files_sharing/lib/External/Manager.php to getRemoteOcsController and then that static function adds the second one, here: https://github.com/SURFnet/rd-sram-integration/blob/20b4723/federatedgroups/lib/AppInfo/Application.php#L147-L148

But this is irrelevant now because we are going to change this code in #117. So this close this issue as wont-fix/superseded.
