### ISSUE TITLE
It seems the getShares method of the OcsRemoteController has wrong logic in returning the result

### ISSUE THREAD

**Issue by soltanireza65** [SURFnet/rd-sram-integration#90]
https://github.com/pondersource/core/blob/7a65b7030effc6a9da234364ed435e7e4a5100fc/apps/files_sharing/lib/Controller/RemoteOcsController.php#L139

actually, the result of the function call in this line must be appended to the final result, and not returned immediately.

**Comment by soltanireza65** [comment]
https://github.com/SURFnet/rd-sram-integration/blob/2bb9359dd46d3d80b37324257aceaf2d5c3be71a/federatedgroups/lib/FilesSharing/Controller/RemoteOcsController.php#L135

**Comment by soltanireza65** [comment]
this is somewhat related to https://github.com/SURFnet/rd-sram-integration/issues/89
if its go to refactor the action or not

**Comment by soltanireza65** [comment]
since we decide to not change the https://github.com/SURFnet/rd-sram-integration/issues/89, so this is correct to

**Comment by michielbdejong** [comment]
The logic is actually correct, except that the mechanism used is the "shadow child" pattern so we are going to change it to the "config+DI" pattern in #117.
