### ISSUE TITLE
Remove share from local oc_share if OCM invites errored

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#92]
The MixedGroupShareProvider first adds an entry into oc_share and then sends OCM invites.
When this fails, the local share should be removed from the oc_share table.

**Comment by thepeak99** [comment]
Related to #31.

Needs more discussion

**Comment by soltanireza65** [comment]
@michielbdejong 
can you pls just write down the scenario so that I can follow it through the code?
I do not know how `MixedGroupShareProvider` relates to the issue, 
because sharing a file with a remote group is in the `files_sharing` app which we have replaced the controllers in `ocm` app

**Comment by soltanireza65** [comment]
so the flow starts with files_sharing/lib/Share20OcsController:createShare
